import { useEffect, useState } from 'react';
import { navigateTo } from '../../routes/AppRoutes';
import { listVouchers, PAYMENT_METHOD_LABELS, VOUCHER_STATUS_LABELS, type Voucher } from './api';
const money=(v:number)=>new Intl.NumberFormat('vi-VN').format(v||0);
export function CommissionPaymentVouchersPage(){
 const [items,setItems]=useState<Voucher[]>([]); const [f,setF]=useState<Record<string,string>>({page:'1',page_size:'20'}); const [loading,setLoading]=useState(false);
 useEffect(()=>{setLoading(true); listVouchers(f).then(r=>setItems(r.data.items)).finally(()=>setLoading(false));},[JSON.stringify(f)]);
 return <section className="page-card"><div className="page-header"><div><h1>Phiếu chi hoa hồng</h1><p>Theo dõi phiếu chi hoa hồng sale để đối soát chi trả theo từng COM và hợp đồng.</p></div></div>
 <div className="filters"><input placeholder="Tìm mã phiếu / mã hợp đồng / mã COM" onChange={e=>setF({...f,q:e.target.value})}/><select onChange={e=>setF({...f,status:e.target.value})}><option value="">Tất cả trạng thái</option><option value="draft">Nháp</option><option value="paid">Đã chi</option><option value="cancelled">Đã hủy</option></select><select onChange={e=>setF({...f,payment_method:e.target.value})}><option value="">Tất cả phương thức</option><option value="cash">Tiền mặt</option><option value="bank_transfer">Chuyển khoản</option><option value="other">Khác</option></select><input type="date" onChange={e=>setF({...f,payment_date_from:e.target.value})}/><input type="date" onChange={e=>setF({...f,payment_date_to:e.target.value})}/></div>
 <table><thead><tr><th>Mã phiếu</th><th>Trạng thái</th><th>Ngày chi</th><th>Sale nhận</th><th>Hợp đồng</th><th>Mã hoa hồng</th><th>Số tiền</th><th>Phương thức</th><th>Người chi</th><th>Ngày tạo</th><th>Hành động</th></tr></thead><tbody>{items.map(v=><tr key={v.id}><td>{v.code}</td><td>{VOUCHER_STATUS_LABELS[v.status]||v.status_label}</td><td>{v.payment_date}</td><td>{v.sale_name}</td><td>{v.contract_code}</td><td>{v.sales_commission_code}</td><td>{money(v.amount)}</td><td>{PAYMENT_METHOD_LABELS[v.payment_method]||v.payment_method_label}</td><td>{v.paid_by_name||'—'}</td><td>{v.created_at?.slice(0,10)}</td><td><button onClick={()=>navigateTo(`/commission-payment-vouchers/${v.id}`)}>Chi tiết</button></td></tr>)}</tbody></table>{loading&&<p>Đang tải...</p>}</section>
}
