import { useEffect, useState } from 'react';import { queryFilters } from '../../utils/urlFilters';
import { Pagination } from '../../components/common/Pagination';
import { navigateTo } from '../../routes/AppRoutes';
import { formatApiError } from '../../services/apiClient';
import { listVouchers, PAYMENT_METHOD_LABELS, VOUCHER_STATUS_LABELS, type Voucher } from './api';
import { GuideBox } from '../../components/help/GuideBox';
import { HelpLabel, HelpTooltip } from '../../components/help/HelpTooltip';
import { tooltipTexts } from '../help/helpContent';
const money=(v:number)=>new Intl.NumberFormat('vi-VN').format(v||0);
const initialFilters:Record<string,string>={page:'1',page_size:'20',q:'',status:'',payment_method:'',payment_date_from:'',payment_date_to:''};
export function CommissionPaymentVouchersPage(){
 const url=queryFilters<Record<string,string>>({}); const hydrated={...initialFilters,...url,payment_date_from:url.date_from||url.payment_date_from||'',payment_date_to:url.date_to||url.payment_date_to||''}; const [items,setItems]=useState<Voucher[]>([]); const [draft,setDraft]=useState<Record<string,string>>(hydrated); const [f,setF]=useState<Record<string,string>>(hydrated); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [meta,setMeta]=useState({page:1,total_pages:1,total:0});
 const set=(k:string,v:string)=>setDraft(current=>({...current,[k]:v}));
 const apply=()=>setF({...draft,page:'1'}); const reset=()=>{setDraft(initialFilters);setF(initialFilters)};
 useEffect(()=>{let active=true;setLoading(true);setError(''); listVouchers(f).then(r=>{if(!active)return; const total=Number(r.data.total||0); const pageSize=Number(f.page_size||20); setItems(Array.isArray(r.data.items)?r.data.items:[]); setMeta({page:Number(f.page||1),total_pages:Math.max(1,Math.ceil(total/pageSize)),total});}).catch(e=>{if(!active)return;setItems([]);setMeta({page:Number(f.page||1),total_pages:1,total:0});setError(formatApiError(e,'Không thể tải danh sách phiếu chi hoa hồng.').join('\n'))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[f]);
 return <section className="page-card"><div className="page-header"><div><h1>Phiếu chi hoa hồng</h1><p>Theo dõi phiếu chi hoa hồng sale để đối soát chi trả theo từng COM và hợp đồng.</p></div></div>
 <GuideBox title="Cách hiểu phiếu chi hoa hồng" items={["Mỗi lần chi hoa hồng sale tạo một phiếu chi.", "Phiếu nháp chưa tính vào đã chi.", "Phiếu đã chi được cộng vào số đã chi sale."]} />
 <div className="filters"><input placeholder="Tìm mã phiếu / mã hợp đồng / mã COM" value={draft.q} onChange={e=>set('q',e.target.value)}/><select value={draft.status} onChange={e=>set('status',e.target.value)}><option value="">Tất cả trạng thái</option><option value="draft">Nháp</option><option value="paid">Đã chi</option><option value="cancelled">Đã hủy</option></select><select value={draft.payment_method} onChange={e=>set('payment_method',e.target.value)}><option value="">Tất cả phương thức</option><option value="cash">Tiền mặt</option><option value="bank_transfer">Chuyển khoản</option><option value="other">Khác</option></select><input type="date" value={draft.payment_date_from} onChange={e=>set('payment_date_from',e.target.value)}/><input type="date" value={draft.payment_date_to} onChange={e=>set('payment_date_to',e.target.value)}/><button type="button" onClick={apply}>Lọc</button><button type="button" className="secondary-button" onClick={reset}>Xóa lọc</button></div>
 {error&&<p className="form-error">{error}</p>}<div className="responsive-table-wrap"><table><thead><tr><th><HelpLabel content={tooltipTexts.paymentReference}>Mã phiếu</HelpLabel></th><th><HelpLabel content={tooltipTexts.draftVoucher + ' ' + tooltipTexts.paidVoucher}>Trạng thái</HelpLabel></th><th>Ngày chi</th><th>Sale nhận</th><th>Hợp đồng</th><th>Mã hoa hồng</th><th>Số tiền</th><th>Phương thức</th><th>Người chi</th><th>Ngày tạo</th><th>Hành động <HelpTooltip content={tooltipTexts.documentLink + ' ' + tooltipTexts.cancelVoucher} /></th></tr></thead><tbody>{items.map(v=><tr key={v.id}><td>{v.code}</td><td>{VOUCHER_STATUS_LABELS[v.status]||v.status_label}</td><td>{v.payment_date}</td><td>{v.sale_name}</td><td>{v.contract_code}</td><td>{v.sales_commission_code}</td><td>{money(v.amount)}</td><td>{PAYMENT_METHOD_LABELS[v.payment_method]||v.payment_method_label}</td><td>{v.paid_by_name||'—'}</td><td>{v.created_at?.slice(0,10)}</td><td><button onClick={()=>navigateTo(`/commission-payment-vouchers/${v.id}`)}>Chi tiết</button></td></tr>)}</tbody></table></div>{loading&&<p>Đang tải...</p>}{!loading&&!error&&items.length===0&&<p className="empty-state">Không có dữ liệu phù hợp.</p>}<Pagination currentPage={meta.page} totalPages={meta.total_pages} totalItems={meta.total} itemLabel="phiếu chi" loading={loading} onPageChange={(page)=>setF(current=>({...current,page:String(page)}))}/></section>
}
