import { useEffect, useState } from 'react';
import { navigateTo } from '../../routes/AppRoutes';
import { DashboardDateRangeFilter } from './DashboardDateRangeFilter';
import { getFinanceDashboard } from './api';
import type { DashboardPreset, FinanceDashboard as Data } from './types';

const money = (v: number | null | undefined) => `${new Intl.NumberFormat('vi-VN').format(Number(v || 0))} đ`;
const num = (v: number | null | undefined) => new Intl.NumberFormat('vi-VN').format(Number(v || 0));
const metrics = [['Doanh số hợp đồng','contract_revenue','/contracts?status=signed,active,completed',true],['Tiền đã thu','collected_amount','/receipts?status=confirmed',true],['Còn phải thu','outstanding_amount','/contracts?payment_status=outstanding',true],['Lịch thanh toán đến hạn','due_schedule_count','/payments?due=true'],['Thanh toán quá hạn','overdue_schedule_count','/payments?overdue=true'],['Phiếu thu chờ xác nhận','pending_receipt_count','/receipts?status=pending'],['Hóa đơn nháp','draft_invoice_count','/invoices?invoice_status=draft'],['Hóa đơn đã phát hành','issued_invoice_count','/invoices?invoice_status=issued'],['Hoa hồng đã duyệt','commission_approved','/commissions?commission_status=approved',true],['Hoa hồng đã chi','commission_paid','/commissions?commission_status=paid',true],['Hoa hồng còn phải chi','commission_outstanding','/commissions?commission_status=approved',true],['Phiếu chi hoa hồng chờ xử lý','pending_commission_voucher_count','/commission-payment-vouchers?status=pending']];
function Table({title, rows}:{title:string;rows:any[]}) { return <section className="card dashboard-table-card"><h3>{title}</h3><div className="responsive-table-wrap"><table><thead><tr>{Object.keys(rows[0] || {}).filter(x=>x!=='id').map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r,i)=><tr key={r.id || i}>{Object.entries(r).filter(([k])=>k!=='id').map(([k,v])=><td key={k}>{typeof v === 'number' ? num(v) : String(v || '—')}</td>)}</tr>) : <tr><td>Chưa có dữ liệu.</td></tr>}</tbody></table></div></section> }
export function FinanceDashboard() { const today=new Date().toISOString().slice(0,10); const [preset,setPreset]=useState<DashboardPreset>('last_30_days'); const [fromDate,setFromDate]=useState(today); const [toDate,setToDate]=useState(today); const [data,setData]=useState<Data|null>(null); useEffect(()=>{void getFinanceDashboard({preset,fromDate,toDate}).then(x=>setData(x.data));},[preset,fromDate,toDate]); if(!data)return <section className="page-card">Đang tải tổng quan tài chính…</section>; const s=data.summary; const q=`date_from=${data.range.from_date}&date_to=${data.range.to_date}`; return <div className="dashboard-page"><header className="page-header dashboard-header"><div><p className="eyebrow">Dashboard · Finance</p><h1>Tổng quan tài chính</h1><p>Theo dõi doanh số, dòng tiền, công nợ, hóa đơn, phiếu thu và hoa hồng.</p></div></header><DashboardDateRangeFilter preset={preset} fromDate={fromDate} toDate={toDate} onChange={x=>{setPreset(x.preset);setFromDate(x.fromDate);setToDate(x.toDate)}}/><section className="dashboard-kpi-section"><h2>Tổng quan dòng tiền</h2><div className="summary-grid dashboard-section-grid">{metrics.slice(0,3).map(([l,k,p,c])=><button className="card summary-card kpi-cash" key={k} onClick={()=>navigateTo(`${p}&${q}`)}><span>{l}</span><strong>{c?money(s[k]):num(s[k])}</strong><small>Xem chi tiết</small></button>)}<article className="card summary-card kpi-cash"><span>Tỷ lệ thu tiền</span><strong>{s.collection_rate == null ? '—' : `${(Number(s.collection_rate)*100).toFixed(1)}%`}</strong></article></div></section><section className="dashboard-kpi-section"><h2>Thanh toán, phiếu thu, hóa đơn & hoa hồng</h2><div className="summary-grid dashboard-section-grid">{metrics.slice(3).map(([l,k,p,c])=><button className="card summary-card kpi-cash" key={k} onClick={()=>navigateTo(`${p}&${q}`)}><span>{l}</span><strong>{c?money(s[k]):num(s[k])}</strong><small>Xem chi tiết</small></button>)}</div></section><section className="dashboard-kpi-section"><h2>Cảnh báo tài chính</h2><div className="summary-grid dashboard-section-grid">{data.alerts.map(a=><article className="card summary-card" key={a.key}><span>{a.label}</span><strong>{num(a.count)}</strong></article>)}</div></section><div className="dashboard-section-grid"><Table title="Thanh toán quá hạn" rows={data.tables.overdue_payments}/><Table title="Phiếu thu chờ xác nhận" rows={data.tables.pending_receipts}/><Table title="Hợp đồng còn phải thu" rows={data.tables.outstanding_contracts}/></div></div> }
