import { useEffect, useState } from 'react';
import { HelpLabel } from '../../components/help/HelpTooltip';
import { navigateTo } from '../../routes/AppRoutes';
import { DashboardDateRangeFilter } from './DashboardDateRangeFilter';
import { getFinanceDashboard } from './api';
import type { DashboardPreset, FinanceDashboard as Data } from './types';

const money=(v:number|null|undefined)=>`${new Intl.NumberFormat('vi-VN').format(Number(v||0))} đ`;
const count=(v:number|null|undefined)=>new Intl.NumberFormat('vi-VN').format(Number(v||0));
const cards=[
 ['Doanh số hợp đồng','contract_revenue','Tổng giá trị hợp đồng hợp lệ trong khoảng thời gian đã chọn.','/contracts?status=signed,active,completed',true],['Tiền đã thu','collected_amount','Tổng tiền từ phiếu thu đã xác nhận trong khoảng thời gian đã chọn.','/receipts?status=confirmed',true],['Còn phải thu','outstanding_amount','Tổng số tiền còn phải thu từ hợp đồng chưa thu đủ.','/contracts?payment_status=outstanding',true],['Lịch thanh toán đến hạn','due_schedule_count','Số lịch thanh toán đến hạn trong khoảng đã chọn và chưa thu đủ.','/payments?due=true'],['Thanh toán quá hạn','overdue_schedule_count','Lịch thanh toán đã quá hạn và còn số tiền chưa thu.','/payments?overdue=true'],['Phiếu thu chờ xác nhận','pending_receipt_count','Phiếu thu chưa được xác nhận.','/receipts?status=draft'],['Hóa đơn nháp','draft_invoice_count','Hóa đơn đang ở trạng thái bản nháp.','/invoices?invoice_status=draft'],['Hóa đơn đã phát hành','issued_invoice_count','Hóa đơn đã phát hành trong khoảng thời gian đã chọn.','/invoices?invoice_status=issued'],['Hoa hồng đã duyệt','commission_approved','Tổng hoa hồng đã được duyệt.','/commissions?status=approved',true],['Hoa hồng đã chi','commission_paid','Tổng hoa hồng đã chi.','/commissions?status=paid',true],['Hoa hồng còn phải chi','commission_outstanding','Hoa hồng đã duyệt trừ hoa hồng đã chi.','/commissions?status=remaining',true],['Phiếu chi hoa hồng chờ xử lý','pending_commission_voucher_count','Phiếu chi hoa hồng chưa hoàn tất xử lý.','/commission-payment-vouchers?status=draft']];
const headers:Record<string,string>={payment_code:'Mã thanh toán',receipt_code:'Mã phiếu thu',contract_code:'Mã hợp đồng',customer_name:'Khách hàng',due_date:'Hạn thanh toán',payment_date:'Ngày thu',expected_amount:'Số tiền phải thu',paid_amount:'Đã thu',remaining_amount:'Còn lại',amount:'Số tiền',creator_name:'Người tạo',status:'Trạng thái',contract_value:'Giá trị hợp đồng'};
function Table({title,rows}:{title:string;rows:any[]}){const keys=Object.keys(rows[0]||{}).filter(k=>k!=='id');return <section className="card dashboard-table-card"><h3>{title}</h3><div className="responsive-table-wrap"><table><thead><tr>{keys.map(k=><th key={k}>{headers[k]||k}</th>)}<th>Chi tiết</th></tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{keys.map(k=><td key={k}>{typeof r[k]==='number'?count(r[k]):String(r[k]||'—')}</td>)}<td><button onClick={()=>navigateTo(kinds(title,r))}>Chi tiết</button></td></tr>):<tr><td colSpan={keys.length+1}>Chưa có dữ liệu.</td></tr>}</tbody></table></div></section>}
function kinds(title:string,r:any){return title==='Thanh toán quá hạn'?`/payments?overdue=true`:title==='Phiếu thu chờ xác nhận'?`/receipts?status=draft`:`/contracts/${r.id}`}
export function FinanceDashboard(){const today=new Date().toISOString().slice(0,10);const[preset,setPreset]=useState<DashboardPreset>('last_30_days');const[fromDate,setFromDate]=useState(today);const[toDate,setToDate]=useState(today);const[data,setData]=useState<Data|null>(null);useEffect(()=>{void getFinanceDashboard({preset,fromDate,toDate}).then(r=>setData(r.data));},[preset,fromDate,toDate]);if(!data)return <section className="page-card">Đang tải tổng quan tài chính…</section>;const s=data.summary,q=`date_from=${data.range.from_date}&date_to=${data.range.to_date}`;const Card=({x}:{x:any})=>{const[l,k,tip,path,isMoney]=x;return <button className="card summary-card kpi-cash" onClick={()=>navigateTo(`${path}&${q}`)}><span><HelpLabel content={tip}>{l}</HelpLabel></span><strong>{isMoney?money(s[k]):count(s[k])}</strong></button>};return <div className="dashboard-page"><header className="page-header dashboard-header"><div><p className="eyebrow">Dashboard · Finance</p><h1>Tổng quan tài chính</h1><p>Theo dõi doanh số, dòng tiền, công nợ, hóa đơn, phiếu thu và hoa hồng.</p></div></header><DashboardDateRangeFilter preset={preset} fromDate={fromDate} toDate={toDate} onChange={x=>{setPreset(x.preset);setFromDate(x.fromDate);setToDate(x.toDate)}}/><section className="dashboard-kpi-section"><h2>Tổng quan dòng tiền</h2><div className="summary-grid dashboard-section-grid">{cards.slice(0,3).map((x,i)=><Card key={i} x={x}/>)}<article className="card summary-card kpi-cash"><span><HelpLabel content="Tiền đã thu chia cho doanh số hợp đồng.">Tỷ lệ thu tiền</HelpLabel></span><strong>{s.collection_rate==null?'—':`${(Number(s.collection_rate)*100).toFixed(1)}%`}</strong></article></div></section><section className="dashboard-kpi-section"><h2>Thanh toán, phiếu thu, hóa đơn & hoa hồng</h2><div className="summary-grid dashboard-section-grid">{cards.slice(3).map((x,i)=><Card key={i} x={x}/>)}</div></section><section className="dashboard-kpi-section"><h2>Cảnh báo tài chính</h2><div className="summary-grid dashboard-section-grid">{data.alerts.map(a=><article className="card summary-card" key={a.key}><span><HelpLabel content={a.label}>{a.label}</HelpLabel></span><strong>{count(a.count)}</strong></article>)}</div></section><div className="dashboard-section-grid"><Table title="Thanh toán quá hạn" rows={data.tables.overdue_payments}/><Table title="Phiếu thu chờ xác nhận" rows={data.tables.pending_receipts}/><Table title="Hợp đồng còn phải thu" rows={data.tables.outstanding_contracts}/></div></div>}
