import { useEffect, useMemo, useState } from 'react';
import { HelpLabel } from '../../components/help/HelpTooltip';
import { navigateTo } from '../../routes/AppRoutes';
import { DashboardDateRangeFilter } from './DashboardDateRangeFilter';
import { getSaleDashboard } from './api';
import type { DashboardPreset, SaleDashboard as Data } from './types';

const n = (v: unknown) => Number.isFinite(Number(v)) ? new Intl.NumberFormat('vi-VN').format(Number(v)) : '—';
const money = (v: unknown) => Number.isFinite(Number(v)) ? `${new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 0 }).format(Number(v))} đ` : '—';
const pct = (v: unknown) => Number.isFinite(Number(v)) ? `${(Number(v) * 100).toFixed(1)}%` : '—';
// Tooltip hover format: dd/MM/yyyy; x-axis label format: dd.
const fullDate = (d: string) => { const p = d.split('-'); return p.length === 3 ? `${p[2]}/${p[1]}/${p[0]}` : d; };
const drill = (path: string, params: Record<string, string> = {}) => { const q = new URLSearchParams(params); navigateTo(`${path}${q.toString() ? `?${q}` : ''}`); };

type Row = { date: string; label?: string; count?: number; amount?: number };
function AreaChart({ title, rows, valueType = 'count' }: { title: string; rows: Row[]; valueType?: 'count' | 'money' }) {
  const values = rows.slice(-30).map((r) => ({ label: r.label || r.date.slice(-2), fullLabel: fullDate(r.date), value: Number(valueType === 'money' ? r.amount : r.count) || 0 }));
  const max = Math.max(1, ...values.map((x) => x.value)); const w = 640, h = 260, px = 34, pt = 22, pb = 44, cw = w - px * 2, ch = h - pt - pb;
  const points = values.map((r, i) => ({ x: px + (values.length === 1 ? cw / 2 : i * cw / Math.max(values.length - 1, 1)), y: pt + ch - r.value / max * ch, r }));
  const line = points.map((p) => `${p.x},${p.y}`).join(' '); const base = h - pb; const area = points.length ? `${px},${base} ${line} ${w - px},${base}` : '';
  return <section className="card dashboard-chart-card dashboard-area-card"><div className="chart-card-heading"><h3>{title}</h3><span>{values.length ? `Tổng: ${valueType === 'money' ? money(values.reduce((s, x) => s + x.value, 0)) : n(values.reduce((s, x) => s + x.value, 0))}` : 'Chưa có dữ liệu'}</span></div><div className="dashboard-area-chart" role="img" aria-label={title}><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><polygon points={area} fill="rgba(37,99,235,.18)"/><polyline points={line} className="area-line"/>{values.map((r, i) => { const p = points[i]; return <g key={`${title}-${r.fullLabel}`}><circle cx={p.x} cy={p.y} r="3" className="area-dot"><title>{`${r.fullLabel}: ${valueType === 'money' ? money(r.value) : n(r.value)}`}</title></circle><text x={p.x} y={base + 22} className="area-tick-label">{r.label}</text></g>; })}</svg></div></section>;
}
function Funnel({ data }: { data: Data['funnel'] }) { const steps = [{ label: 'Lead', value: data.lead_count, color: '#2563eb' }, { label: 'Customer', value: data.customer_count, color: '#38bdf8' }, { label: 'Booking', value: data.booking_count, color: '#14b8a6' }, { label: 'Deposit', value: data.deposit_count, color: '#22c55e' }, { label: 'Deal', value: data.deal_count, color: '#f59e0b' }, { label: 'Contract', value: data.contract_count, color: '#7c3aed' }]; const max = Math.max(1, ...steps.map((s) => Number(s.value || 0))); return <section className="card dashboard-funnel-card trapezoid-funnel-card"><h3>Funnel Lead → Contract</h3><div className="trapezoid-funnel">{steps.map((s, i) => <div className="trapezoid-segment" style={{ width: `${Math.max(42, 100 - i * 10, Number(s.value || 0) / max * 100)}%`, background: s.color }} key={s.label}><span>{s.label}</span><strong>{n(s.value)}</strong></div>)}</div></section>; }
function Kpi({ icon, label, value, help, to }: { icon: string; label: string; value: string; help: string; to?: () => void }) { const inner = <><span className="summary-icon-badge">{icon}</span><HelpLabel content={help}>{label}</HelpLabel><strong className="summary-value">{value}</strong></>; return to ? <button type="button" role="link" tabIndex={0} className="summary-card kpi-button" onClick={to}>{inner}</button> : <div className="summary-card">{inner}</div>; }
export function SaleDashboard() {
  const [preset, setPreset] = useState<DashboardPreset>('last_7_days'); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState(''); const [data, setData] = useState<Data | null>(null);
  useEffect(() => { let alive = true; getSaleDashboard({ preset, startDate: fromDate, endDate: toDate }).then((r) => { if (alive) setData(r.data); }); return () => { alive = false; }; }, [preset, fromDate, toDate]);
  const s = data?.summary || {}; const dated = { scope: 'mine', preset, start_date: fromDate, end_date: toDate };
  const kpis = useMemo(() => [
    ['☑','Công việc hôm nay',n(s.task_today_count),'Số công việc đến hạn trong ngày hôm nay.',()=>drill('/tasks/today',{scope:'mine'})], ['⚠','Công việc quá hạn',n(s.task_overdue_count),'Số công việc đã quá hạn và chưa hoàn thành.',()=>drill('/tasks/overdue',{scope:'mine'})], ['📅','Lịch hẹn hôm nay',n(s.appointment_today_count),'Số lịch hẹn diễn ra trong ngày hôm nay.',()=>drill('/appointments/today',{scope:'mine'})], ['!','Lịch hẹn quá hạn',n(s.appointment_overdue_count),'Số lịch hẹn đã quá thời gian xử lý.',()=>drill('/appointments',{scope:'mine',status:'overdue'})], ['↻','Lead cần chăm sóc hôm nay',n(s.lead_care_today_count),'Các lead đến hạn chăm sóc trong hôm nay.',()=>drill('/leads',{scope:'mine',care_due:'today',next_follow_up:'today'})], ['⚠','Lead quá hạn chăm sóc',n(s.lead_overdue_count),'Các lead đã quá ngày chăm sóc tiếp theo.',()=>drill('/leads/overdue',{scope:'mine',care_status:'overdue'})],
    ['◦','Lead mới',n(s.lead_new_count),'Các lead mới do bạn tạo trong khoảng thời gian.',()=>drill('/leads',{...dated,created_from:fromDate,created_to:toDate})], ['✓','Lead đang chăm sóc',n(s.lead_active_count),'Các lead đang trong trạng thái chăm sóc.',()=>drill('/leads',{scope:'mine',status:'active'})], ['?','Lead chưa có hoạt động',n(s.lead_without_activity_count),'Số lead chưa có hoạt động chăm sóc nào được ghi nhận.',()=>drill('/leads',{scope:'mine',activity_status:'none',has_activity:'false'})], ['👥','Khách hàng',n(s.customer_count),'Số khách hàng bạn đang phụ trách.',()=>drill('/customers',{scope:'mine'})], ['7d','Khách lâu chưa tương tác',n(s.customer_stale_count),'Số khách/lead lâu chưa có tương tác mới.',()=>drill('/leads',{scope:'mine',stale:'true'})],
    ['□','Booking',n(s.booking_count),'Số booking/giữ chỗ trong khoảng thời gian.',()=>drill('/bookings',dated)], ['●','Khách đã cọc',n(s.deposit_count),'Số giao dịch đã ghi nhận cọc.',()=>drill('/deals',{scope:'mine',stage:'deposit'})], ['◇','Deal',n(s.deal_count),'Số deal/giao dịch bạn phụ trách.',()=>drill('/deals',{scope:'mine'})], ['✓','Hợp đồng ký',n(s.contract_signed_count),'Số hợp đồng hợp lệ trong khoảng thời gian.',()=>drill('/contracts',{scope:'mine',status:'valid'})], ['$','Doanh số',money(s.revenue_total),'Tổng giá trị hợp đồng hợp lệ của bạn trong khoảng thời gian.',()=>drill('/contracts',{scope:'mine',status:'valid'})], ['◈','Tiền khách đã thu',money(s.customer_paid_total),'Tổng tiền khách đã thanh toán được ghi nhận.',()=>drill('/receipts',{scope:'mine'})],
    ['✓','HH đã duyệt',money(s.sales_commission_approved_total),'Hoa hồng của bạn đã được duyệt.',()=>drill('/commissions',{scope:'mine'})], ['→','HH đã chi',money(s.sales_commission_paid_total),'Hoa hồng của bạn đã được chi.',()=>drill('/commissions',{scope:'mine'})], ['…','HH còn phải chi',money(s.sales_commission_outstanding_total),'Hoa hồng đã duyệt nhưng chưa chi.',()=>drill('/commissions',{scope:'mine'})], ['%','Tỷ lệ Lead → Khách',pct(s.lead_to_customer_rate),'Tỷ lệ chuyển đổi từ lead sang khách hàng.'], ['%','Tỷ lệ chi HH',pct(s.sales_commission_payment_rate),'Tỷ lệ hoa hồng đã chi trên hoa hồng đã duyệt.']
  ], [s, preset, fromDate, toDate]);
  if (!data) return <section className="page-card">Đang tải dashboard sale...</section>;
  return <div className="page dashboard-page boss-dashboard sale-dashboard"><div className="dashboard-content"><header className="page-header dashboard-header"><div><p className="eyebrow">Dashboard · Sale</p><h1>Dashboard của tôi</h1><p>Trung tâm điều hướng công việc, KPI, pipeline, doanh số và hoa hồng cá nhân.</p></div></header><DashboardDateRangeFilter preset={preset} fromDate={fromDate} toDate={toDate} onChange={(x)=>{setPreset(x.preset);setFromDate(x.fromDate);setToDate(x.toDate);}}/><section className="dashboard-kpi-section"><div className="summary-grid dashboard-section-grid">{kpis.map((k) => <Kpi key={k[1] as string} icon={k[0] as string} label={k[1] as string} value={k[2] as string} help={k[3] as string} to={k[4] as (()=>void)|undefined}/>)}</div></section><section className="dashboard-section-block"><h2>Xu hướng</h2><div className="dashboard-grid dashboard-section-grid trend-grid"><AreaChart title="Doanh số theo ngày" rows={data.time_series.revenue_by_day} valueType="money"/><AreaChart title="Lead theo ngày" rows={data.time_series.leads_by_day}/></div></section><section className="dashboard-section-block"><h2>Funnel</h2><Funnel data={data.funnel}/></section><section className="dashboard-section-block"><h2>Danh sách cần xử lý</h2><div className="dashboard-section-grid">{data.priority.map((x) => <section className="card detail-list-card" key={x.title}><strong>{x.title}</strong><button className="link-button" onClick={()=>navigateTo(x.url)}>Open</button></section>)}</div></section></div></div>;
}
