import { useCallback, useEffect, useState } from 'react';
import { Pagination } from '../../components/common/Pagination';
import { navigateTo } from '../../routes/AppRoutes';
import { formatApiError } from '../../services/apiClient';
import { queryFilters } from '../../utils/urlFilters';
import { listInvoices } from '../payments/api';
import type { PaymentInvoice } from '../payments/types';
const money=(v:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(v);const pageSize=20;
export function InvoicesPage(){const url=queryFilters<Record<string,string>>({});const[items,setItems]=useState<PaymentInvoice[]>([]);const[q,setQ]=useState(url.q||'');const[status,setStatus]=useState(url.invoice_status||url.status||'');const[page,setPage]=useState(1);const[meta,setMeta]=useState({page:1,total:0,total_pages:1});const[loading,setLoading]=useState(false);const[error,setError]=useState('');const load=useCallback(async(nextPage=page,next={q,status})=>{setLoading(true);try{const r=await listInvoices({...url,...next,status:next.status,page:String(nextPage),page_size:String(pageSize)});setItems(Array.isArray(r.data)?r.data:[]);setMeta({page:Number(r.meta.page||nextPage),total:Number(r.meta.total||0),total_pages:Number(r.meta.total_pages||1)});setError('')}catch(e){setError(formatApiError(e,'Không thể tải danh sách hóa đơn.').join('. '))}finally{setLoading(false)}},[q,status,page]);useEffect(()=>{void load()},[load]);return <div className="admin-page"><header className="page-header"><div><h1>Hóa đơn</h1><p>Quản lý hóa đơn và chứng từ thanh toán.</p></div></header><div className="filter-bar"><input value={q} placeholder="Tìm mã hóa đơn, hợp đồng, khách hàng" onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="draft">Nháp</option><option value="issued">Đã phát hành</option><option value="cancelled">Đã hủy</option></select><button onClick={()=>{setPage(1);void load(1)}}>Tìm kiếm</button></div>{error&&<p className="form-error">{error}</p>}<div className="table-card"><table><thead><tr><th>Mã hóa đơn</th><th>Hợp đồng</th><th>Khách hàng</th><th>Số tiền</th><th>Ngày phát hành</th><th>Trạng thái</th><th /></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.invoice_code}</td><td>{i.contract?.contract_code||'—'}</td><td>{i.customer?.full_name||'—'}</td><td>{money(i.amount)}</td><td>{i.issued_date?new Date(i.issued_date).toLocaleDateString('vi-VN'):'Chưa phát hành'}</td><td>{i.status_label}</td><td><button onClick={()=>navigateTo(`/invoices/${i.id}`)}>Chi tiết</button></td></tr>)}</tbody></table></div><Pagination currentPage={meta.page} totalPages={meta.total_pages} totalItems={meta.total} itemLabel="hóa đơn" loading={loading} onPageChange={setPage}/></div>}
