import { useEffect, useState } from 'react';
import { can } from '../auth/authStore';
import { navigateTo } from '../../routes/AppRoutes';
import { downloadCommissionReconciliationCsv, getCommissionReconciliationReport, type ReportResponse } from './api';
const money=(v:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(v||0);
const statusLabels:Record<string,string>={ok:'Bình thường',company_not_fully_received:'Công ty chưa thu đủ',sale_unpaid:'Sale chưa được chi',sale_partially_paid:'Sale đã chi một phần',sale_paid:'Sale đã chi đủ',draft_voucher_pending:'Có phiếu nháp',over_paid:'Chi vượt',over_received:'Thu vượt',blocked_by_policy:'Bị chặn theo chính sách',no_company_commission:'Chưa có hoa hồng công ty',no_sales_commission:'Chưa có hoa hồng sale'};
const empty={page:'1',page_size:'20',date_from:'',date_to:'',project_id:'',sale_id:'',reconciliation_status:'',q:''};
export function CommissionReconciliationReportPage(){
 const [filters,setFilters]=useState<Record<string,string>>(empty);const [applied,setApplied]=useState<Record<string,string>>(empty);const [data,setData]=useState<ReportResponse|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{setLoading(true);setError('');getCommissionReconciliationReport(applied).then(setData).catch(()=>setError('Không tải được báo cáo đối soát hoa hồng.')).finally(()=>setLoading(false))},[applied]);
 const apply=()=>setApplied({...filters,page:'1'}); const reset=()=>{setFilters(empty);setApplied(empty)}; const exp=()=>downloadCommissionReconciliationCsv(applied).catch(()=>setError('Không thể xuất CSV đối soát hoa hồng.'));
 const s=data?.summary; const items=data?.items ?? []; const cards=s?[['HH công ty xác nhận',money(s.total_company_commission_confirmed)],['HH công ty đã nhận',money(s.total_company_commission_received)],['HH công ty còn phải thu',money(s.total_company_commission_remaining)],['HH sale đã duyệt',money(s.total_sales_commission_approved)],['Đã chi sale',money(s.total_sales_commission_paid)],['Còn phải chi sale',money(s.total_sales_commission_remaining)],['Phiếu chi nháp',s.draft_voucher_count],['Bị chặn theo chính sách',s.blocked_by_policy_count]]:[];
 return <div className="admin-page commissions-page commission-reconciliation-page"><header className="page-header"><div><h1>Báo cáo đối soát hoa hồng</h1><p>Theo dõi hoa hồng công ty đã thu, hoa hồng sale đã duyệt, phiếu chi đã chi và số còn phải đối soát.</p></div>{can('reports.commission_reconciliation.export')&&<button onClick={exp}>Xuất CSV</button>}</header>
 <div className="filter-bar filter-panel commission-filter-panel"><label>Từ ngày<input type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/></label><label>Đến ngày<input type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/></label><label>Dự án<input placeholder="ID dự án" value={filters.project_id} onChange={e=>setFilters({...filters,project_id:e.target.value})}/></label><label>Sale<input placeholder="ID sale" value={filters.sale_id} onChange={e=>setFilters({...filters,sale_id:e.target.value})}/></label><label>Trạng thái đối soát<select value={filters.reconciliation_status} onChange={e=>setFilters({...filters,reconciliation_status:e.target.value})}><option value="">Tất cả</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Tìm kiếm<input value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder="Mã HĐ, khách hàng, dự án, sale..."/></label><div className="filter-actions"><button onClick={apply}>Lọc</button><button type="button" onClick={reset}>Xóa lọc</button></div></div>
 {s&&<section className="metric-grid commission-kpi-grid">{cards.map(([l,v])=><article className="metric-card" key={String(l)}><span>{l}</span><strong>{v}</strong></article>)}</section>}
 {error&&<p className="form-error">{error}</p>}{loading&&<p>Đang tải báo cáo...</p>}
 <section className="commission-table-card"><div className="responsive-table-wrap commission-table-scroll"><table><thead><tr>{['Hợp đồng','Dự án','Khách hàng','Sale','HH công ty xác nhận','HH công ty đã nhận','HH công ty còn phải thu','HH sale đã duyệt','Đã chi sale','Còn phải chi sale','Chính sách chi','Hạn mức còn có thể chi','Phiếu nháp','Phiếu đã chi','Trạng thái đối soát','Hành động'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.map(r=><tr key={r.sales_commission_id}><td>{r.contract_code}</td><td>{r.project_name||'—'}</td><td>{r.customer_name||'—'}</td><td>{r.sale_name||'—'}</td><td>{money(r.company_commission_confirmed_amount)}</td><td>{money(r.company_commission_received_amount)}</td><td>{money(r.company_commission_remaining_amount)}</td><td>{money(r.sales_commission_approved_amount)}</td><td>{money(r.sales_commission_paid_amount)}</td><td>{money(r.sales_commission_remaining_amount)}</td><td>{r.payout_policy_label||'—'}<br/><small>{r.payout_policy_source_label||''}</small></td><td>{money(r.remaining_payable_capacity)}</td><td>{r.voucher_draft_count}</td><td>{r.voucher_paid_count}</td><td><strong>{statusLabels[r.reconciliation_status]||'Bình thường'}</strong><br/><small>{(r.reconciliation_flags ?? []).map(x=>statusLabels[x]||x).join(', ')}</small></td><td><div className="table-actions commission-row-actions"><button onClick={()=>navigateTo(`/contracts/${r.contract_id}`)}>Xem hợp đồng</button><button onClick={()=>navigateTo(`/commissions/${r.sales_commission_id}`)}>Xem HH sale</button>{r.company_commission_id&&<button onClick={()=>navigateTo(`/company-commissions/${r.company_commission_id}`)}>Xem HH công ty</button>}<button onClick={()=>navigateTo('/commission-payment-vouchers')}>Xem phiếu chi</button></div></td></tr>)}</tbody></table>{!loading&&items.length===0&&<p className="empty-state">Chưa có dữ liệu đối soát hoa hồng.</p>}</div></section></div>
}
