DEFAULT_ROLES = [{'code': 'admin', 'description': 'System administrator', 'name': 'Admin'},
 {'code': 'director', 'description': 'Executive/director access', 'name': 'Director'},
 {'code': 'sales_manager', 'description': 'Sales department manager', 'name': 'Sales Manager'},
 {'code': 'leader', 'description': 'Sales team leader', 'name': 'Leader'},
 {'code': 'sale', 'description': 'Salesperson', 'name': 'Sale'},
 {'code': 'marketing', 'description': 'Marketing team', 'name': 'Marketing'},
 {'code': 'accountant', 'description': 'Finance/accounting team', 'name': 'Accountant'},
 {'code': 'inventory_manager', 'description': 'Inventory/project manager', 'name': 'Inventory Manager'},
 {'code': 'viewer', 'description': 'Read-only limited role', 'name': 'Viewer'}]

PERMISSION_CODES_BY_MODULE = {'activities': ['activities.view.own',
                'activities.view.team',
                'activities.view.all',
                'activities.create',
                'activities.update.own',
                'activities.update.team',
                'activities.delete'],
 'audit_logs': ['audit_logs.view', 'audit_logs.export'],
 'commissions': ['commissions.view.own',
                 'commissions.view.team',
                 'commissions.view.all',
                 'commissions.update',
                 'commissions.approve',
                 'commissions.mark_paid',
                 'commissions.export'],
 'customers': ['customers.view.own',
               'customers.view.team',
               'customers.view.department',
               'customers.view.all',
               'customers.create',
               'customers.update.own',
               'customers.update.team',
               'customers.update.department',
               'customers.update.all',
               'customers.delete',
               'customers.assign.own',
               'customers.assign.team',
               'customers.assign.department',
               'customers.assign.all',
               'customers.add_activity.own',
               'customers.add_activity.team',
               'customers.add_activity.department',
               'customers.add_activity.all'],
 'dashboard': ['dashboard.view.own', 'dashboard.view.team', 'dashboard.view.all'],
 'deals': ['deals.view.own',
           'deals.view.team',
           'deals.view.department',
           'deals.view.all',
           'deals.create',
           'deals.update.own',
           'deals.update.team',
           'deals.update.department',
           'deals.update.all',
           'deals.assign.own',
           'deals.assign.team',
           'deals.assign.department',
           'deals.assign.all',
           'deals.stage.own',
           'deals.stage.team',
           'deals.stage.department',
           'deals.stage.all',
           'deals.status.own',
           'deals.status.team',
           'deals.status.department',
           'deals.status.all',
           'deals.add_activity.own',
           'deals.add_activity.team',
           'deals.add_activity.department',
           'deals.add_activity.all',
           'deals.delete.own',
           'deals.delete.team',
           'deals.delete.department',
           'deals.delete.all'],
 'inventory': ['inventory.projects.view.all',
               'inventory.projects.create',
               'inventory.projects.update',
               'inventory.projects.delete',
               'inventory.properties.view.own',
               'inventory.properties.view.team',
               'inventory.properties.view.department',
               'inventory.properties.view.all',
               'inventory.properties.create',
               'inventory.properties.update.own',
               'inventory.properties.update.team',
               'inventory.properties.update.department',
               'inventory.properties.update.all',
               'inventory.properties.status.own',
               'inventory.properties.status.team',
               'inventory.properties.status.department',
               'inventory.properties.status.all',
               'inventory.properties.delete.own',
               'inventory.properties.delete.team',
               'inventory.properties.delete.department',
               'inventory.properties.delete.all',
               'inventory.properties.price.view.own',
               'inventory.properties.price.view.team',
               'inventory.properties.price.view.department',
               'inventory.properties.price.view.all',
               'inventory.properties.price.update.own',
               'inventory.properties.price.update.team',
               'inventory.properties.price.update.department',
               'inventory.properties.price.update.all'],
 'lead_appointments': ['lead_appointments.view.own',
                       'lead_appointments.view.team',
                       'lead_appointments.view.all',
                       'lead_appointments.create',
                       'lead_appointments.update.own',
                       'lead_appointments.update.team',
                       'lead_appointments.update.all',
                       'lead_appointments.delete',
                       'lead_appointments.complete.own',
                       'lead_appointments.complete.team',
                       'lead_appointments.complete.all'],
 'lead_tasks': ['lead_tasks.view.own',
                'lead_tasks.view.team',
                'lead_tasks.view.all',
                'lead_tasks.create',
                'lead_tasks.update.own',
                'lead_tasks.update.team',
                'lead_tasks.update.all',
                'lead_tasks.delete',
                'lead_tasks.complete.own',
                'lead_tasks.complete.team',
                'lead_tasks.complete.all'],
 'leads': ['leads.view.own',
           'leads.view.team',
           'leads.view.department',
           'leads.view.all',
           'leads.create',
           'leads.import',
           'leads.update.own',
           'leads.update.team',
           'leads.update.all',
           'leads.assign.team',
           'leads.assign.all',
           'leads.reclaim.team',
           'leads.reclaim.all',
           'leads.delete',
           'leads.export',
           'leads.convert.own',
           'leads.convert.team',
           'leads.convert.department',
           'leads.convert.all'],
 'marketing': ['marketing.view',
               'marketing.create_campaign',
               'marketing.update_campaign',
               'marketing.delete_campaign',
               'marketing.import_leads',
               'marketing.view_roi',
               'marketing.export'],
 'payments': ['payments.view', 'payments.view_all', 'payments.create', 'payments.update', 'payments.confirm', 'payments.cancel', 'payments.approve', 'payments.export'],
 'permissions': ['permissions.view'],
 'reports': ['reports.view.own',
             'reports.view.team',
             'reports.view.department',
             'reports.view.all',
             'reports.view.ceo_dashboard',
             'reports.view.marketing_roi',
             'reports.view.finance',
             'reports.export'],
 'roles': ['roles.view', 'roles.create', 'roles.update', 'roles.assign_permissions'],
 'settings': ['settings.manage_master_data',
              'settings.manage_status',
              'settings.manage_workflow',
              'settings.manage_permissions',
              'settings.manage_integrations'],
 'users': ['users.view', 'users.create', 'users.update', 'users.deactivate']}

ALL_PERMISSION_CODES = [code for codes in PERMISSION_CODES_BY_MODULE.values() for code in codes]

ROLE_PERMISSION_MAP = {'accountant': ['payments.view',
                'payments.create',
                'payments.update',
                'payments.confirm',
                'payments.cancel',
                'payments.approve',
                'payments.export',
                'commissions.view.all',
                'commissions.update',
                'commissions.approve',
                'commissions.mark_paid',
                'commissions.export',
                'reports.view.finance',
                'reports.export'],
 'admin': ['activities.view.own',
           'activities.view.team',
           'activities.view.all',
           'activities.create',
           'activities.update.own',
           'activities.update.team',
           'activities.delete',
           'audit_logs.view',
           'audit_logs.export',
           'commissions.view.own',
           'commissions.view.team',
           'commissions.view.all',
           'commissions.update',
           'commissions.approve',
           'commissions.mark_paid',
           'commissions.export',
           'customers.view.own',
           'customers.view.team',
           'customers.view.department',
           'customers.view.all',
           'customers.create',
           'customers.update.own',
           'customers.update.team',
           'customers.update.department',
           'customers.update.all',
           'customers.delete',
           'customers.assign.own',
           'customers.assign.team',
           'customers.assign.department',
           'customers.assign.all',
           'customers.add_activity.own',
           'customers.add_activity.team',
           'customers.add_activity.department',
           'customers.add_activity.all',
           'dashboard.view.own',
           'dashboard.view.team',
           'dashboard.view.all',
           'lead_appointments.view.own',
           'lead_appointments.view.team',
           'lead_appointments.view.all',
           'lead_appointments.create',
           'lead_appointments.update.own',
           'lead_appointments.update.team',
           'lead_appointments.update.all',
           'lead_appointments.delete',
           'lead_appointments.complete.own',
           'lead_appointments.complete.team',
           'lead_appointments.complete.all',
           'lead_tasks.view.own',
           'lead_tasks.view.team',
           'lead_tasks.view.all',
           'lead_tasks.create',
           'lead_tasks.update.own',
           'lead_tasks.update.team',
           'lead_tasks.update.all',
           'lead_tasks.delete',
           'lead_tasks.complete.own',
           'lead_tasks.complete.team',
           'lead_tasks.complete.all',
           'leads.view.own',
           'leads.view.team',
           'leads.view.department',
           'leads.view.all',
           'leads.create',
           'leads.import',
           'leads.update.own',
           'leads.update.team',
           'leads.update.all',
           'leads.assign.team',
           'leads.assign.all',
           'leads.reclaim.team',
           'leads.reclaim.all',
           'leads.delete',
           'leads.export',
           'leads.convert.own',
           'leads.convert.team',
           'leads.convert.department',
           'leads.convert.all',
           'marketing.view',
           'marketing.create_campaign',
           'marketing.update_campaign',
           'marketing.delete_campaign',
           'marketing.import_leads',
           'marketing.view_roi',
           'marketing.export',
           'payments.view',
           'payments.create',
           'payments.update',
           'payments.confirm',
           'payments.cancel',
           'payments.approve',
           'payments.export',
           'permissions.view',
           'reports.view.own',
           'reports.view.team',
           'reports.view.department',
           'reports.view.all',
           'reports.view.ceo_dashboard',
           'reports.view.marketing_roi',
           'reports.view.finance',
           'reports.export',
           'roles.view',
           'roles.create',
           'roles.update',
           'roles.assign_permissions',
           'settings.manage_master_data',
           'settings.manage_status',
           'settings.manage_workflow',
           'settings.manage_permissions',
           'settings.manage_integrations',
           'users.view',
           'users.create',
           'users.update',
           'users.deactivate',
           'deals.view.own',
           'deals.view.team',
           'deals.view.department',
           'deals.view.all',
           'deals.create',
           'deals.update.own',
           'deals.update.team',
           'deals.update.department',
           'deals.update.all',
           'deals.assign.own',
           'deals.assign.team',
           'deals.assign.department',
           'deals.assign.all',
           'deals.stage.own',
           'deals.stage.team',
           'deals.stage.department',
           'deals.stage.all',
           'deals.status.own',
           'deals.status.team',
           'deals.status.department',
           'deals.status.all',
           'deals.add_activity.own',
           'deals.add_activity.team',
           'deals.add_activity.department',
           'deals.add_activity.all',
           'deals.delete.own',
           'deals.delete.team',
           'deals.delete.department',
           'deals.delete.all',
           'inventory.projects.view.all',
           'inventory.projects.create',
           'inventory.projects.update',
           'inventory.projects.delete',
           'inventory.properties.view.own',
           'inventory.properties.view.team',
           'inventory.properties.view.department',
           'inventory.properties.view.all',
           'inventory.properties.create',
           'inventory.properties.update.own',
           'inventory.properties.update.team',
           'inventory.properties.update.department',
           'inventory.properties.update.all',
           'inventory.properties.status.own',
           'inventory.properties.status.team',
           'inventory.properties.status.department',
           'inventory.properties.status.all',
           'inventory.properties.delete.own',
           'inventory.properties.delete.team',
           'inventory.properties.delete.department',
           'inventory.properties.delete.all',
           'inventory.properties.price.view.own',
           'inventory.properties.price.view.team',
           'inventory.properties.price.view.department',
           'inventory.properties.price.view.all',
           'inventory.properties.price.update.own',
           'inventory.properties.price.update.team',
           'inventory.properties.price.update.department',
           'inventory.properties.price.update.all'],
 'director': ['lead_tasks.view.all',
              'lead_tasks.update.all',
              'lead_tasks.complete.all',
              'lead_appointments.view.all',
              'lead_appointments.update.all',
              'lead_appointments.complete.all',
              'dashboard.view.all',
              'customers.view.all',
              'leads.view.all',
              'activities.view.all',
              'marketing.view',
              'marketing.view_roi',
              'payments.view',
              'commissions.view.all',
              'reports.view.all',
              'reports.view.ceo_dashboard',
              'reports.view.marketing_roi',
              'reports.view.finance',
              'reports.export',
              'audit_logs.view',
              'customers.update.all',
              'customers.assign.all',
              'customers.add_activity.all',
              'leads.convert.all',
              'deals.view.all',
              'deals.update.all',
              'deals.assign.all',
              'deals.stage.all',
              'deals.status.all',
              'deals.add_activity.all',
              'inventory.projects.view.all',
              'inventory.projects.update',
              'inventory.properties.view.all',
              'inventory.properties.create',
              'inventory.properties.update.all',
              'inventory.properties.status.all',
              'inventory.properties.price.view.all',
              'inventory.properties.price.update.all'],
 'inventory_manager': ['inventory.projects.view.all',
                       'inventory.projects.create',
                       'inventory.projects.update',
                       'inventory.projects.delete',
                       'inventory.properties.view.own',
                       'inventory.properties.view.team',
                       'inventory.properties.view.department',
                       'inventory.properties.view.all',
                       'inventory.properties.create',
                       'inventory.properties.update.own',
                       'inventory.properties.update.team',
                       'inventory.properties.update.department',
                       'inventory.properties.update.all',
                       'inventory.properties.status.own',
                       'inventory.properties.status.team',
                       'inventory.properties.status.department',
                       'inventory.properties.status.all',
                       'inventory.properties.delete.own',
                       'inventory.properties.delete.team',
                       'inventory.properties.delete.department',
                       'inventory.properties.delete.all',
                       'inventory.properties.price.view.own',
                       'inventory.properties.price.view.team',
                       'inventory.properties.price.view.department',
                       'inventory.properties.price.view.all',
                       'inventory.properties.price.update.own',
                       'inventory.properties.price.update.team',
                       'inventory.properties.price.update.department',
                       'inventory.properties.price.update.all'],
 'leader': ['lead_tasks.view.team',
            'lead_tasks.create',
            'lead_tasks.update.team',
            'lead_tasks.complete.team',
            'lead_appointments.view.team',
            'lead_appointments.create',
            'lead_appointments.update.team',
            'lead_appointments.complete.team',
            'dashboard.view.team',
            'customers.view.team',
            'customers.create',
            'customers.update.team',
            'leads.view.team',
            'leads.create',
            'leads.update.team',
            'leads.assign.team',
            'leads.reclaim.team',
            'activities.view.team',
            'activities.create',
            'reports.view.team',
            'customers.assign.team',
            'customers.add_activity.team',
            'leads.convert.team',
            'deals.view.team',
            'deals.create',
            'deals.update.team',
            'deals.assign.team',
            'deals.stage.team',
            'deals.status.team',
            'deals.add_activity.team',
            'inventory.projects.view.all',
            'inventory.properties.view.team',
            'inventory.properties.create',
            'inventory.properties.update.team',
            'inventory.properties.status.team',
            'inventory.properties.price.view.team',
            'inventory.properties.price.update.team'],
 'marketing': ['leads.view.all',
               'leads.create',
               'leads.import',
               'marketing.view',
               'marketing.create_campaign',
               'marketing.update_campaign',
               'marketing.import_leads',
               'marketing.view_roi',
               'marketing.export',
               'reports.view.marketing_roi',
               'reports.export'],
 'sale': ['lead_tasks.view.own',
          'lead_tasks.create',
          'lead_tasks.update.own',
          'lead_tasks.complete.own',
          'lead_appointments.view.own',
          'lead_appointments.create',
          'lead_appointments.update.own',
          'lead_appointments.complete.own',
          'dashboard.view.own',
          'customers.view.own',
          'customers.create',
          'customers.update.own',
          'leads.view.own',
          'leads.create',
          'leads.update.own',
          'activities.view.own',
          'activities.create',
          'reports.view.own',
          'commissions.view.own',
          'customers.assign.own',
          'customers.add_activity.own',
          'leads.convert.own',
          'deals.view.own',
          'deals.create',
          'deals.update.own',
          'deals.stage.own',
          'deals.status.own',
          'deals.add_activity.own',
          'inventory.projects.view.all',
          'inventory.properties.view.own',
          'inventory.properties.create',
          'inventory.properties.update.own',
          'inventory.properties.status.own',
          'inventory.properties.price.view.own'],
 'sales_manager': ['lead_tasks.view.team',
                   'lead_tasks.create',
                   'lead_tasks.update.team',
                   'lead_tasks.complete.team',
                   'lead_appointments.view.team',
                   'lead_appointments.create',
                   'lead_appointments.update.team',
                   'lead_appointments.complete.team',
                   'dashboard.view.team',
                   'customers.view.department',
                   'customers.create',
                   'customers.update.all',
                   'leads.view.department',
                   'leads.create',
                   'leads.update.all',
                   'leads.assign.all',
                   'leads.reclaim.all',
                   'activities.view.all',
                   'activities.create',
                   'reports.view.department',
                   'reports.export',
                   'customers.update.department',
                   'customers.assign.department',
                   'customers.add_activity.department',
                   'leads.convert.department',
                   'deals.view.department',
                   'deals.create',
                   'deals.update.department',
                   'deals.assign.department',
                   'deals.stage.department',
                   'deals.status.department',
                   'deals.add_activity.department',
                   'inventory.projects.view.all',
                   'inventory.projects.create',
                   'inventory.projects.update',
                   'inventory.properties.view.department',
                   'inventory.properties.create',
                   'inventory.properties.update.department',
                   'inventory.properties.status.department',
                   'inventory.properties.price.view.department',
                   'inventory.properties.price.update.department'],
 'viewer': ['reports.view.own',
            'customers.view.own',
            'deals.view.own',
            'inventory.projects.view.all',
            'inventory.properties.view.own',
            'inventory.properties.price.view.own']}

# Sprint 11: Booking / reservation / deposit permissions.
BOOKING_PERMISSIONS = [
    *[f"bookings.view.{scope}" for scope in ("own", "team", "department", "all")],
    "bookings.create",
    *[f"bookings.update.{scope}" for scope in ("own", "team", "department", "all")],
    *[f"bookings.status.{scope}" for scope in ("own", "team", "department", "all")],
    *[f"bookings.delete.{scope}" for scope in ("own", "team", "department", "all")],
    *[f"bookings.refund.{scope}" for scope in ("own", "team", "department", "all")],
]
PERMISSION_CODES_BY_MODULE["bookings"] = BOOKING_PERMISSIONS
ROLE_PERMISSION_MAP["admin"].extend(BOOKING_PERMISSIONS)
ROLE_PERMISSION_MAP["director"].extend(["bookings.view.all", "bookings.update.all", "bookings.status.all", "bookings.refund.all"])
ROLE_PERMISSION_MAP["sales_manager"].extend(["bookings.view.department", "bookings.create", "bookings.update.department", "bookings.status.department", "bookings.refund.department"])
ROLE_PERMISSION_MAP["leader"].extend(["bookings.view.team", "bookings.create", "bookings.update.team", "bookings.status.team", "bookings.refund.team"])
ROLE_PERMISSION_MAP["sale"].extend(["bookings.view.own", "bookings.create", "bookings.update.own", "bookings.status.own"])
ROLE_PERMISSION_MAP["viewer"].append("bookings.view.own")

CONTRACT_PERMISSIONS = [
    *[f"contracts.view.{scope}" for scope in ("own", "team", "department", "all")], "contracts.create",
    *[f"contracts.update.{scope}" for scope in ("own", "team", "department", "all")],
    *[f"contracts.status.{scope}" for scope in ("own", "team", "department", "all")],
    *[f"contracts.delete.{scope}" for scope in ("own", "team", "department", "all")],
    *[f"contracts.payment.view.{scope}" for scope in ("own", "team", "department", "all")], "contracts.payment.create",
    *[f"contracts.payment.update.{scope}" for scope in ("own", "team", "department", "all")],
    *[f"contracts.payment.confirm.{scope}" for scope in ("own", "team", "department", "all")],
]
PERMISSION_CODES_BY_MODULE["contracts"] = CONTRACT_PERMISSIONS
ALL_PERMISSION_CODES = sorted({code for codes in PERMISSION_CODES_BY_MODULE.values() for code in codes})
ROLE_PERMISSION_MAP["admin"] = list(ALL_PERMISSION_CODES)
ROLE_PERMISSION_MAP["director"] += [code for code in CONTRACT_PERMISSIONS if ".delete." not in code and code != "contracts.create"]
ROLE_PERMISSION_MAP["sales_manager"] += ["contracts.create", "contracts.view.department", "contracts.update.department", "contracts.status.department", "contracts.payment.view.department", "contracts.payment.create", "contracts.payment.update.department", "contracts.payment.confirm.department"]
ROLE_PERMISSION_MAP["leader"] += ["contracts.create", "contracts.view.team", "contracts.update.team", "contracts.status.team", "contracts.payment.view.team", "contracts.payment.create", "contracts.payment.update.team", "contracts.payment.confirm.team"]
ROLE_PERMISSION_MAP["sale"] += ["contracts.create", "contracts.view.own", "contracts.update.own", "contracts.status.own", "contracts.payment.view.own", "contracts.payment.create", "contracts.payment.update.own"]
ROLE_PERMISSION_MAP["viewer"] += ["contracts.view.own", "contracts.payment.view.own"]


# Sprint 14: Task and in-app notification permissions.
TASK_PERMISSIONS = ["tasks.view", "tasks.create", "tasks.update", "tasks.complete", "tasks.cancel", "tasks.assign", "tasks.view_all"]
NOTIFICATION_PERMISSIONS = ["notifications.view", "notifications.update"]
PERMISSION_CODES_BY_MODULE["tasks"] = TASK_PERMISSIONS
PERMISSION_CODES_BY_MODULE["notifications"] = NOTIFICATION_PERMISSIONS
ALL_PERMISSION_CODES = sorted({code for codes in PERMISSION_CODES_BY_MODULE.values() for code in codes})
ROLE_PERMISSION_MAP["admin"] = list(ALL_PERMISSION_CODES)
ROLE_PERMISSION_MAP["director"] += ["tasks.view_all", "tasks.update", "tasks.complete", "notifications.view", "notifications.update"]
ROLE_PERMISSION_MAP["sales_manager"] += ["tasks.view_all", "tasks.create", "tasks.update", "tasks.complete", "tasks.cancel", "tasks.assign", "notifications.view", "notifications.update"]
ROLE_PERMISSION_MAP["leader"] += ["tasks.view", "tasks.create", "tasks.update", "tasks.complete", "tasks.cancel", "tasks.assign", "notifications.view", "notifications.update"]
ROLE_PERMISSION_MAP["sale"] += ["tasks.view", "tasks.create", "tasks.update", "tasks.complete", "tasks.cancel", "notifications.view", "notifications.update"]
ROLE_PERMISSION_MAP["viewer"] += ["tasks.view", "notifications.view"]
