import { useEffect, useState, type FormEvent } from 'react';
import { Modal } from '../../components/Modal';
import { FormError } from '../../components/FormError';
import { formatApiError } from '../../services/apiClient';
import { eligibleCompanyCommissionContracts, generateCompanyCommission, approveCompanyCommission, receiveCompanyCommission, holdCompanyCommission, cancelCompanyCommission } from './api';
import type { CompanyCommission, EligibleContract } from './types';
const LEGAL_STATUS_REASON = 'Hợp đồng chưa đủ trạng thái pháp lý để tạo hoa hồng công ty.';
const money=(v:any)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(Number(v||0));
function Context({item}:{item:CompanyCommission}){return <section className="context-card"><strong>Bạn đang thao tác hoa hồng công ty:</strong><p>{item.receivable_code} • HĐ {item.contract_code} • Bên trả hoa hồng {item.commission_payer_name||'Chưa cập nhật'} • Khách hàng {item.customer_name||'Chưa cập nhật'}</p><p>HH dự kiến {money(item.expected_commission_amount)} • HH xác nhận {money(item.confirmed_receivable_amount)} • Đã nhận {money(item.received_amount)} • Còn phải thu {money(item.remaining_amount)} • Trạng thái {item.status}</p></section>}
export function CreateCompanyCommissionModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [keyword,setKeyword]=useState('');const [items,setItems]=useState<EligibleContract[]>([]);const [selected,setSelected]=useState<EligibleContract|null>(null);const [rate,setRate]=useState('2');const [date,setDate]=useState('');const [note,setNote]=useState('');const [errors,setErrors]=useState<string[]>([]);useEffect(()=>{eligibleCompanyCommissionContracts({keyword,limit:20}).then(r=>setItems(r.data.items||[])).catch(e=>setErrors(formatApiError(e)))},[keyword]);const expected=(Number(selected?.contract_value||0)*Number(rate||0)/100);async function submit(e:FormEvent){e.preventDefault();if(!selected)return;try{await generateCompanyCommission({contract_id:selected.contract_id,commission_rate_percent:Number(rate),expected_receive_date:date||null,note});onSaved()}catch(err){setErrors(formatApiError(err))}}return <Modal title="Tạo hoa hồng công ty từ hợp đồng" onClose={onClose}><form className="admin-form" onSubmit={submit}><label>Tìm hợp đồng<input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Mã HĐ / khách hàng"/></label><div className="list-panel">{items.map(c=><button type="button" className="contract-option" disabled={!c.is_eligible_for_company_commission} onClick={()=>setSelected(c)} key={c.contract_id}><strong>{c.contract_code}</strong> — {c.customer_name||'Chưa cập nhật'} — {money(c.contract_value)}<br/>Sale: {c.sale_name||'Chưa gán'} • Vai trò công ty: {c.company_role} • Bên bán thực tế: {c.actual_seller_name||c.actual_seller_type||'Chưa cập nhật'} • Bên trả hoa hồng: {c.commission_payer_name||c.commission_payer_type||'Chưa cập nhật'} • Mã hợp đồng/chính sách môi giới: {c.brokerage_contract_code||'Chưa cập nhật'}{c.reason&&<small className="error-text">{c.reason}</small>}</button>)}</div><label>Tỷ lệ hoa hồng công ty (%)<input type="number" min="0.01" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Hoa hồng dự kiến tự tính<input readOnly value={money(expected)}/></label><label>Ngày dự kiến nhận<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Ghi chú<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><FormError messages={errors}/><footer className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Hủy</button><button disabled={!selected?.is_eligible_for_company_commission||!Number(rate)}>Tạo hoa hồng công ty</button></footer></form></Modal>}
export function ActionModal({item,type,onClose,onSaved}:{item:CompanyCommission;type:'approve'|'receive'|'hold'|'cancel';onClose:()=>void;onSaved:()=>void}){const [amount,setAmount]=useState(String(type==='approve'?item.expected_commission_amount:''));const [reason,setReason]=useState('');const [date,setDate]=useState('');const [note,setNote]=useState('');const [errors,setErrors]=useState<string[]>([]);async function submit(e:FormEvent){e.preventDefault();try{if(type==='approve')await approveCompanyCommission(item.id,{confirmed_receivable_amount:Number(amount),note});if(type==='receive')await receiveCompanyCommission(item.id,{amount_received_now:Number(amount),received_date:date||null,note});if(type==='hold')await holdCompanyCommission(item.id,{hold_reason:reason,note});if(type==='cancel')await cancelCompanyCommission(item.id,{cancel_reason:reason,note});onSaved()}catch(err){setErrors(formatApiError(err))}}const title={approve:'Duyệt hoa hồng công ty',receive:'Ghi nhận đã nhận tiền',hold:'Tạm giữ hoa hồng công ty',cancel:'Hủy hoa hồng công ty'}[type];return <Modal title={title} onClose={onClose}><form className="admin-form" onSubmit={submit}><Context item={item}/>{type==='cancel'&&<p className="error-text">Khoản hoa hồng công ty đã nhận tiền không được hủy.</p>}{type==='approve'&&<label>Hoa hồng xác nhận<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}{type==='receive'&&<><label>Số tiền nhận lần này<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Ngày nhận<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></>}{type==='hold'&&<label>Lý do tạm giữ<input required value={reason} onChange={e=>setReason(e.target.value)}/></label>}{type==='cancel'&&<label>Lý do hủy<input required value={reason} onChange={e=>setReason(e.target.value)}/></label>}<label>Ghi chú<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><FormError messages={errors}/><footer className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Đóng</button><button>{title}</button></footer></form></Modal>}
