export type GlossaryTerm = { term: string; group: string; description: string; example?: string; modules?: string[] };
export type HelpSection = { title: string; items: string[]; groups?: { title: string; items: string[] }[] };

export const tooltipTexts = {
  eligibleCommission: 'Hoa hồng đủ điều kiện tính theo hợp đồng và khoản khách đã thanh toán.',
  approvedCommission: 'Số tiền hoa hồng sale đã được quản lý duyệt.',
  paidAmount: 'Tổng tiền đã chi qua phiếu chi đã xác nhận.',
  remainingSalesCommission: 'Số tiền còn lại chưa chi cho sale.',
  commissionStatus: 'Trạng thái xử lý hoa hồng sale trong quy trình duyệt và chi.',
  createPaymentVoucher: 'Tạo chứng từ cho một lần chi hoa hồng sale.',
  payoutPolicy: 'Quy tắc xác định khi nào được chi hoa hồng sale và được chi tối đa bao nhiêu.',
  remainingPayableCapacity: 'Số tiền tối đa còn được chi tại thời điểm hiện tại theo chính sách.',
  companyConfirmed: 'Số tiền hoa hồng công ty dự kiến hoặc đã xác nhận sẽ nhận.',
  companyReceived: 'Số tiền công ty đã thực nhận.',
  companyRemaining: 'Số tiền công ty còn chưa nhận.',
  commissionPayer: 'Bên có trách nhiệm trả hoa hồng cho công ty: chủ đầu tư, chủ nhà, chủ đất hoặc đối tác.',
  receiveCompanyCommission: 'Ghi nhận số tiền hoa hồng công ty đã thực nhận.',
  draftVoucher: 'Phiếu đã tạo nhưng chưa xác nhận chi tiền, chưa cộng vào số đã chi sale.',
  paidVoucher: 'Phiếu đã xác nhận chi tiền và được cộng vào số đã chi sale.',
  cancelVoucher: 'Hủy phiếu không còn hợp lệ theo quy trình được phép.',
  documentLink: 'Đường dẫn tới chứng từ hoặc file đính kèm phục vụ đối soát.',
  paymentReference: 'Mã giao dịch hoặc mã chứng từ dùng để tra cứu lần chi.',
  reconciliationStatus: 'Tình trạng tổng hợp của hợp đồng/hoa hồng dựa trên tiền công ty nhận, hoa hồng sale và phiếu chi.',
  blockedByPolicy: 'Còn tiền sale phải chi nhưng hiện chưa đủ điều kiện chi tiếp.',
  hasDraftVoucher: 'Đang có phiếu chi ở trạng thái nháp cần xác nhận hoặc hủy.',
  policyOption1: 'Sale được chi trong phạm vi tiền hoa hồng công ty đã nhận.',
  policyOption2: 'Sale được chi theo tỷ lệ tương ứng với phần hoa hồng công ty đã thu.',
  systemFallback: 'Chính sách dùng khi dự án/hoa hồng chưa có chính sách riêng.',
  projectDefault: 'Chính sách mặc định áp dụng cho các hoa hồng thuộc dự án này.',
  approvalOverride: 'Chính sách riêng được chọn khi duyệt hoa hồng, nếu hệ thống cho phép.'
};

export const glossaryTerms: GlossaryTerm[] = [
  ['Lead','Khách hàng & Lead','Khách hàng tiềm năng, có thể đến từ quảng cáo, giới thiệu, telesale hoặc nguồn khác.'],
  ['Khách hàng','Khách hàng & Lead','Người đã có thông tin rõ ràng trong hệ thống và có thể phát sinh giao dịch.'],
  ['Booking / Giữ chỗ','Booking & Hợp đồng','Bước khách hàng đặt giữ sản phẩm/căn/hồ sơ trước khi ký hợp đồng chính thức.'],
  ['Hợp đồng','Booking & Hợp đồng','Giao dịch chính thức giữa khách hàng và bên bán/chủ đầu tư/chủ nhà, là cơ sở để tính doanh thu và hoa hồng.'],
  ['Thanh toán','Thanh toán & Hóa đơn','Khoản tiền khách hàng phải trả hoặc đã trả theo hợp đồng.'],
  ['Phiếu thu','Thanh toán & Hóa đơn','Chứng từ ghi nhận công ty đã thu tiền từ khách hàng.'],
  ['Hóa đơn','Thanh toán & Hóa đơn','Chứng từ xuất cho khoản phải thu/thanh toán, không đồng nghĩa tự động đã thu tiền.'],
  ['Hoa hồng công ty','Hoa hồng','Khoản hoa hồng/doanh thu công ty được nhận từ chủ đầu tư, chủ nhà, chủ đất hoặc đối tác.'],
  ['Hoa hồng công ty xác nhận','Hoa hồng','Số tiền hoa hồng công ty được xác nhận sẽ nhận hoặc phải thu.'],
  ['Hoa hồng công ty đã nhận','Hoa hồng','Số tiền hoa hồng công ty đã thực nhận.'],
  ['Hoa hồng công ty còn phải thu','Hoa hồng','Số tiền hoa hồng công ty còn chưa nhận, thường bằng hoa hồng xác nhận trừ hoa hồng đã nhận.'],
  ['Hoa hồng sale','Hoa hồng','Khoản tiền công ty dự kiến hoặc đã duyệt để chi cho sale theo hợp đồng/giao dịch.'],
  ['Hoa hồng sale đã duyệt','Hoa hồng','Số tiền hoa hồng sale đã được quản lý duyệt.'],
  ['Đã chi sale','Phiếu chi','Tổng tiền hoa hồng đã chi cho sale qua phiếu chi đã xác nhận.'],
  ['Còn phải chi sale','Phiếu chi','Số tiền hoa hồng sale còn lại chưa chi, thường bằng hoa hồng sale đã duyệt trừ số đã chi.'],
  ['Chính sách chi hoa hồng','Hoa hồng','Quy tắc xác định khi nào được chi hoa hồng sale và được chi tối đa bao nhiêu.'],
  ['Chi theo hạn mức tiền HH công ty đã nhận','Hoa hồng','Sale được chi tối đa trong phạm vi tiền hoa hồng công ty đã thực nhận.'],
  ['Chi theo tỷ lệ HH công ty đã thu','Hoa hồng','Sale được chi theo tỷ lệ tương ứng với phần hoa hồng công ty đã thu được.'],
  ['Hạn mức còn có thể chi','Hoa hồng','Số tiền tối đa còn được phép chi cho sale tại thời điểm hiện tại theo chính sách.'],
  ['Bị chặn theo chính sách','Báo cáo','Hoa hồng sale còn phải chi nhưng hiện chưa đủ điều kiện chi tiếp do chính sách hoặc tiền hoa hồng công ty đã nhận chưa đủ.'],
  ['Phiếu chi hoa hồng','Phiếu chi','Chứng từ ghi nhận một lần chi hoa hồng cho sale.'],
  ['Phiếu chi nháp','Phiếu chi','Phiếu chi đã tạo nhưng chưa xác nhận đã chi tiền, chưa được tính vào số đã chi sale.'],
  ['Phiếu đã chi','Phiếu chi','Phiếu chi đã xác nhận chi tiền, được tính vào số đã chi sale.'],
  ['Đối soát hoa hồng','Báo cáo','Quá trình so sánh hoa hồng công ty, hoa hồng sale, phiếu chi và số tiền còn phải thu/chi để kiểm tra sai lệch.'],
  ['Sale đã chi đủ','Báo cáo','Hoa hồng sale đã được chi đủ theo số tiền đã duyệt.'],
  ['Sale đã chi một phần','Báo cáo','Hoa hồng sale đã được chi một phần nhưng vẫn còn tiền chưa chi.'],
  ['Sale chưa được chi','Báo cáo','Hoa hồng sale đã duyệt nhưng chưa có phiếu chi đã xác nhận.'],
  ['Có phiếu nháp','Báo cáo','Đang có phiếu chi ở trạng thái nháp cần xác nhận hoặc hủy.'],
  ['Thu vượt','Báo cáo','Số tiền hoa hồng công ty đã nhận lớn hơn số xác nhận, cần kiểm tra lại dữ liệu.'],
  ['Chi vượt','Báo cáo','Số tiền đã chi sale lớn hơn số hoa hồng sale đã duyệt, là cảnh báo nghiêm trọng cần kiểm tra.'],
].map(([term, group, description]) => ({ term, group, description, modules: group === 'Hoa hồng' ? ['Hoa hồng sale', 'Hoa hồng công ty'] : [group] }));

export const helpSections: HelpSection[] = [
 {title:'Tổng quan quy trình CRM BĐS',items:['Lead được tạo từ nguồn quảng cáo, telesale hoặc nhập tay.','Sale chăm sóc lead bằng task, lịch hẹn, ghi chú.','Khi khách hàng quan tâm thực sự, có thể tạo booking/giữ chỗ.','Khi giao dịch chính thức, tạo hợp đồng.','Theo hợp đồng, hệ thống theo dõi thanh toán, phiếu thu, hóa đơn.','Khi đủ điều kiện, hệ thống tạo và duyệt hoa hồng sale.','Công ty ghi nhận hoa hồng công ty phải thu và đã nhận.','Kế toán/sếp lập phiếu chi hoa hồng sale.','Báo cáo đối soát giúp kiểm tra tổng thể.']},
 {title:'Phân biệt Hoa hồng công ty và Hoa hồng sale',items:[],groups:[{title:'Hoa hồng công ty',items:['Là tiền công ty được nhận từ chủ đầu tư/chủ nhà/đối tác.','Là nguồn tiền/điều kiện để xét chi hoa hồng sale.']},{title:'Hoa hồng sale',items:['Là tiền công ty chi cho sale.','Cần được duyệt trước khi chi.','Việc chi có thể bị chặn nếu chưa đủ điều kiện theo chính sách.']}]},
 {title:'Quy trình hoa hồng sale',items:['Tạo hoa hồng sale từ hợp đồng.','Duyệt số tiền hoa hồng sale.','Hệ thống kiểm tra chính sách chi.','Lập phiếu chi hoa hồng.','Có thể lưu nháp hoặc xác nhận đã chi.','Phiếu nháp chưa tính vào đã chi.','Phiếu đã chi mới tính vào đã chi sale.']},
 {title:'Quy trình hoa hồng công ty',items:['Tạo hoa hồng công ty từ hợp đồng.','Xác nhận số tiền công ty phải thu.','Ghi nhận số tiền công ty đã nhận.','Số tiền đã nhận ảnh hưởng đến hạn mức chi sale.']},
 {title:'Khi nào sale bị chặn chi?',items:['Hoa hồng công ty chưa nhận đủ.','Chính sách dự án yêu cầu chi theo tỷ lệ tiền đã thu.','COM đang bị tạm giữ.','Hoa hồng sale chưa được duyệt.','Đã chi đủ hoa hồng sale.','Không có quyền thao tác.']},
 {title:'Phiếu chi hoa hồng',items:['Mỗi lần chi hoa hồng tạo một phiếu chi riêng.','Một COM có thể có nhiều phiếu chi.','Phiếu nháp không cộng vào đã chi.','Phiếu đã chi mới cộng vào đã chi.','Hủy phiếu đã chi sẽ làm giảm số đã chi nếu hệ thống cho phép.']},
 {title:'Báo cáo đối soát hoa hồng',items:['Công ty đã thu bao nhiêu hoa hồng.','Còn phải thu bao nhiêu.','Sale đã được duyệt bao nhiêu.','Đã chi sale bao nhiêu.','Còn phải chi sale bao nhiêu.','Dòng nào bị chặn theo chính sách.','Dòng nào có phiếu nháp.','Có dữ liệu thu vượt/chi vượt không.']},
 {title:'Ý nghĩa các trạng thái đối soát',items:['Bình thường: không có cảnh báo nghiêm trọng.','Công ty chưa thu đủ: hoa hồng công ty còn phải thu.','Sale chưa được chi: hoa hồng sale đã duyệt nhưng chưa chi.','Sale đã chi một phần: đã chi một phần, còn lại chưa chi.','Sale đã chi đủ: đã chi đủ theo số duyệt.','Có phiếu nháp: có phiếu chi chưa xác nhận.','Bị chặn theo chính sách: chưa đủ điều kiện chi tiếp.','Thu vượt: công ty nhận nhiều hơn số xác nhận.','Chi vượt: sale được chi nhiều hơn số duyệt.']},
];
