import { BusinessTimeline } from '../../../components/timeline/BusinessTimeline';
import type { ContractActivity } from '../types';

const ACTIVITY_LABELS: Record<string, string> = {created:'Tạo hợp đồng',updated:'Cập nhật hợp đồng',status_changed:'Đổi trạng thái hợp đồng',payment_created:'Tạo thanh toán hợp đồng',payment_paid:'Xác nhận thanh toán hợp đồng',payment_schedule_created:'Tạo lịch thanh toán',payment_schedule_updated:'Cập nhật lịch thanh toán',payment_schedule_cancelled:'Hủy lịch thanh toán',payment_receipt_confirmed:'Xác nhận phiếu thu',payment_receipt_cancelled:'Hủy phiếu thu',payment_schedule_paid:'Đợt thanh toán đã thanh toán đủ',payment_overdue:'Đợt thanh toán quá hạn',payment_penalty:'Áp dụng phí phạt',payment_invoice_created:'Tạo hóa đơn nháp'};
const formatTime=(value:string)=>new Date(value).toLocaleString('vi-VN');
const formatVnd=(value:string|number|null|undefined)=>{if(value===null||value===undefined||value==='')return 'Chưa cập nhật';const amount=Number(value);return Number.isFinite(amount)?`${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}).format(amount)} đ`:'Chưa cập nhật';};
const show=(v:string|null|undefined)=>v||'Chưa cập nhật';
const labelFor=(a:ContractActivity)=>ACTIVITY_LABELS[a.activity_type]||a.activity_label||a.title||'Hoạt động hợp đồng';
function meta(activity:ContractActivity){const metadata=activity.metadata??{}; if(activity.activity_type==='payment_created') return <dl className="business-timeline-details"><div><dt>Số tiền</dt><dd>{formatVnd(metadata.amount)}</dd></div><div><dt>Loại thanh toán</dt><dd>{show(metadata.payment_type_label)}</dd></div><div><dt>Trạng thái</dt><dd>{show(metadata.payment_status_label)}</dd></div></dl>; if(activity.activity_type==='payment_paid') return <dl className="business-timeline-details"><div><dt>Số tiền</dt><dd>{formatVnd(metadata.amount)}</dd></div><div><dt>Phương thức</dt><dd>{show(metadata.payment_method_label)}</dd></div><div><dt>Mã tham chiếu</dt><dd>{show(metadata.reference_number)}</dd></div><div><dt>Ngày thanh toán</dt><dd>{metadata.paid_date?formatTime(metadata.paid_date):'Chưa cập nhật'}</dd></div></dl>; return null;}
function description(activity:ContractActivity){if(activity.old_value&&activity.new_value) return `Hợp đồng chuyển từ ${activity.old_value} sang ${activity.new_value}.`; return activity.content || activity.title || '';}
export function ContractTimeline({ items }: { items: ContractActivity[] }) {
  return <BusinessTimeline emptyText="Chưa có hoạt động hợp đồng." items={items.map(activity=>({id:activity.id,title:labelFor(activity),time:formatTime(activity.created_at),actor:activity.actor.full_name,description:description(activity),oldValue:activity.old_value,newValue:activity.new_value,meta:meta(activity)}))}/>;
}
