"""deal closing, contracts, and payments foundation

Revision ID: 20260613_0010
Revises: 20260612_0009
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20260613_0010"; down_revision="20260612_0009"; branch_labels=None; depends_on=None

def upgrade():
    op.add_column("deals",sa.Column("booking_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("bookings.id")))
    op.add_column("deals",sa.Column("property_unit_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("property_units.id")))
    op.add_column("deals",sa.Column("project_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("projects.id")))
    for c in ("booking_id","property_unit_id","project_id"): op.create_index(f"ix_deals_{c}","deals",[c])
    op.create_index("ix_deals_booking_deleted_at","deals",["booking_id","deleted_at"]); op.create_index("ix_deals_property_status_deleted_at","deals",["property_unit_id","status","deleted_at"])
    op.create_table("contracts",
        sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("contract_code",sa.String(30),nullable=False),sa.Column("deal_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("deals.id"),nullable=False),sa.Column("booking_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("bookings.id")),sa.Column("customer_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("customers.id"),nullable=False),sa.Column("property_unit_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("property_units.id"),nullable=False),sa.Column("project_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("projects.id")),sa.Column("contract_type",sa.String(30),nullable=False,server_default="deposit_contract"),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("contract_number",sa.String(100)),sa.Column("signed_date",sa.DateTime(timezone=True)),sa.Column("effective_date",sa.DateTime(timezone=True)),sa.Column("handover_date",sa.DateTime(timezone=True)),sa.Column("contract_value",sa.Numeric(18,2),nullable=False),sa.Column("deposit_value",sa.Numeric(18,2)),sa.Column("remaining_value",sa.Numeric(18,2)),sa.Column("buyer_name",sa.String(255)),sa.Column("buyer_phone",sa.String(50)),sa.Column("buyer_email",sa.String(255)),sa.Column("buyer_id_number",sa.String(100)),sa.Column("buyer_address",sa.Text()),sa.Column("seller_name",sa.String(255)),sa.Column("seller_phone",sa.String(50)),sa.Column("seller_email",sa.String(255)),sa.Column("seller_representative",sa.String(255)),sa.Column("note",sa.Text()),sa.Column("created_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id"),nullable=False),sa.Column("updated_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id")),sa.Column("deleted_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("contract_code",name="uq_contracts_contract_code"))
    for c in ("deal_id","booking_id","customer_id","property_unit_id","project_id","status","signed_date","deleted_at"): op.create_index(f"ix_contracts_{c}","contracts",[c])
    op.create_table("contract_payments",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("payment_code",sa.String(30),nullable=False),sa.Column("contract_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("contracts.id"),nullable=False),sa.Column("deal_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("deals.id"),nullable=False),sa.Column("customer_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("customers.id"),nullable=False),sa.Column("property_unit_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("property_units.id"),nullable=False),sa.Column("payment_type",sa.String(30),nullable=False,server_default="payment"),sa.Column("status",sa.String(30),nullable=False,server_default="planned"),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("due_date",sa.DateTime(timezone=True)),sa.Column("paid_date",sa.DateTime(timezone=True)),sa.Column("payment_method",sa.String(100)),sa.Column("reference_number",sa.String(100)),sa.Column("note",sa.Text()),sa.Column("created_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id"),nullable=False),sa.Column("updated_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id")),sa.Column("deleted_by_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("deleted_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("payment_code",name="uq_contract_payments_payment_code"))
    for c in ("contract_id","deal_id","customer_id","property_unit_id","status","due_date","paid_date","deleted_at"): op.create_index(f"ix_contract_payments_{c}","contract_payments",[c])
    op.create_table("contract_activities",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("contract_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("actor_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("users.id"),nullable=False),sa.Column("activity_type",sa.String(30),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("content",sa.Text()),sa.Column("old_value",sa.Text()),sa.Column("new_value",sa.Text()),sa.Column("metadata",postgresql.JSON()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    for c in ("contract_id","actor_id","activity_type","created_at"): op.create_index(f"ix_contract_activities_{c}","contract_activities",[c])

def downgrade():
    op.drop_table("contract_activities"); op.drop_table("contract_payments"); op.drop_table("contracts")
    for n in ("ix_deals_property_status_deleted_at","ix_deals_booking_deleted_at","ix_deals_project_id","ix_deals_property_unit_id","ix_deals_booking_id"): op.drop_index(n,table_name="deals")
    for c in ("project_id","property_unit_id","booking_id"): op.drop_column("deals",c)
