import type { LeadUser } from '../leads/types';
export type TaskStatus='open'|'in_progress'|'done'|'cancelled'; export type TaskType='call_customer'|'follow_up'|'booking_expiry'|'contract_signing'|'payment_due'|'general'; export type TaskPriority='low'|'medium'|'high'|'urgent';
export type TaskUser=LeadUser;
export type LeadTask={id:string;task_code:string;title:string;description:string|null;task_type:TaskType;status:TaskStatus;priority:TaskPriority;due_at:string|null;assigned_user_id:string|null;primary_assignee_id?:string|null;assigned_to_id?:string|null;assigned_user:LeadUser|null;assigned_to?:LeadUser|null;primary_assignee?:LeadUser|null;assignee_ids?:string[];assignees?:TaskUser[];watcher_ids?:string[];watchers?:TaskUser[];created_by_id:string|null;creator?:LeadUser|null;created_by?:LeadUser|null;completed_at:string|null;cancelled_at:string|null;related_customer_id:string|null;related_lead_id:string|null;related_booking_id:string|null;related_deal_id:string|null;related_contract_id:string|null;related_property_unit_id:string|null;related_customer?:{id:string;customer_code:string;full_name:string;primary_phone:string}|null;related_lead?:{id:string;code:string;full_name:string;phone_primary:string}|null;related_booking?:{id:string;booking_code:string}|null;related_deal?:{id:string;deal_code:string;title:string}|null;related_contract?:{id:string;contract_code:string}|null;related_property_unit?:{id:string;property_code:string;title:string}|null;auto_generated:boolean;source_event:string|null;note:string|null;created_at:string;updated_at:string;activities?:Array<{id:string;activity_type:string;title:string;content:string|null;old_value:string|null;new_value:string|null;created_at:string}>};
export type TaskPayload={title:string;description?:string|null;task_type:TaskType;priority:TaskPriority;due_at?:string|null;assigned_user_id?:string|null;primary_assignee_id?:string|null;assignee_ids?:string[];watcher_ids?:string[];related_customer_id?:string|null;related_lead_id?:string|null;related_booking_id?:string|null;related_deal_id?:string|null;related_contract_id?:string|null;related_property_unit_id?:string|null;note?:string|null};

export type TaskComment={id:string;task_id:string;content:string;author:TaskUser|null;created_at:string;updated_at:string;is_deleted:boolean};
export type TaskRelatedLink={id:string;task_id:string;title:string;url:string;note:string|null;created_by:TaskUser|null;created_at:string;updated_at:string};
export type TaskTimelineEvent={id:string;task_id:string;event_type:string;title:string;description:string|null;actor:TaskUser|null;old_value:string|null;new_value:string|null;created_at:string};
