import { useState } from 'react';
import { formatApiError } from '../../services/apiClient';
import { applyPenalty, createInvoice, createPaymentSchedule, createReceipt } from './api';

export function PaymentScheduleForm({ contractId, onSaved }: { contractId?: string; onSaved: () => void }) {
  const [form,setForm]=useState({contract_id:contractId||'',sequence_no:'',title:'',due_date:'',expected_amount:'',note:''}); const [errors,setErrors]=useState<string[]>([]);
  async function submit(e:React.FormEvent){e.preventDefault(); if(!form.contract_id) return setErrors(['Vui lòng chọn hợp đồng.']); if(Number(form.expected_amount)<=0) return setErrors(['Số tiền phải thu phải lớn hơn 0.']); if(!form.due_date) return setErrors(['Ngày đến hạn là bắt buộc.']); try{await createPaymentSchedule({...form,sequence_no:Number(form.sequence_no),expected_amount:Number(form.expected_amount)}); onSaved();}catch(err){setErrors(formatApiError(err));}}
  return <form onSubmit={submit} className="inline-form"><h3>Tạo đợt thanh toán</h3>{errors.length>0&&<div className="form-error">{errors.join('. ')}</div>} {!contractId&&<input placeholder="ID hợp đồng" value={form.contract_id} onChange={e=>setForm({...form,contract_id:e.target.value})}/>}<input type="number" placeholder="Số thứ tự" value={form.sequence_no} onChange={e=>setForm({...form,sequence_no:e.target.value})}/><input placeholder="Tên đợt" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/><input type="number" placeholder="Số tiền phải thu" value={form.expected_amount} onChange={e=>setForm({...form,expected_amount:e.target.value})}/><input placeholder="Ghi chú" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><button type="submit">Tạo lịch thanh toán</button></form>;
}
export function ReceiptForm({ paymentId, onSaved }: { paymentId: string; onSaved: () => void }) { const [form,setForm]=useState({amount:'',payment_date:new Date().toISOString().slice(0,10),payment_method:'bank_transfer',reference_no:'',note:'',status:'confirmed'}); const [errors,setErrors]=useState<string[]>([]); async function submit(e:React.FormEvent){e.preventDefault(); if(Number(form.amount)<=0) return setErrors(['Số tiền thanh toán phải lớn hơn 0.']); try{await createReceipt(paymentId,{...form,amount:Number(form.amount)}); onSaved();}catch(err){setErrors(formatApiError(err));}} return <form onSubmit={submit} className="inline-form"><h3>Ghi nhận thanh toán</h3>{errors.length>0&&<div className="form-error">{errors.join('. ')}</div>}<input type="number" placeholder="Số tiền" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input type="date" value={form.payment_date} onChange={e=>setForm({...form,payment_date:e.target.value})}/><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="bank_transfer">Chuyển khoản</option><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="other">Khác</option></select><input placeholder="Mã giao dịch/chứng từ" value={form.reference_no} onChange={e=>setForm({...form,reference_no:e.target.value})}/><input placeholder="Ghi chú" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="confirmed">Xác nhận thanh toán</option><option value="draft">Lưu bản nháp</option></select><button type="submit">Lưu phiếu thu</button></form>; }
export function PenaltyForm({ paymentId, onSaved }: { paymentId: string; onSaved: () => void }) { const [amount,setAmount]=useState(''); const [reason,setReason]=useState(''); const [errors,setErrors]=useState<string[]>([]); async function submit(e:React.FormEvent){e.preventDefault(); if(Number(amount)<0) return setErrors(['Phí phạt không được âm.']); if(Number(amount)>0&&!reason.trim()) return setErrors(['Phí phạt phải có lý do.']); try{await applyPenalty(paymentId,{penalty_amount:Number(amount),penalty_reason:reason}); onSaved();}catch(err){setErrors(formatApiError(err));}} return <form onSubmit={submit} className="inline-form"><h3>Áp dụng phí phạt</h3>{errors.length>0&&<div className="form-error">{errors.join('. ')}</div>}<input type="number" placeholder="Phí phạt" value={amount} onChange={e=>setAmount(e.target.value)}/><input placeholder="Lý do phí phạt" value={reason} onChange={e=>setReason(e.target.value)}/><button type="submit">Áp dụng phí phạt</button></form>; }
export function InvoiceForm({ paymentId, onSaved }: { paymentId: string; onSaved: () => void }) { async function make(){await createInvoice(paymentId,{issued_date:new Date().toISOString().slice(0,10),status:'draft'}); onSaved();} return <button type="button" onClick={make}>Tạo hóa đơn nháp</button>; }
