import { useCallback, useEffect, useState } from 'react';
import { formatApiError } from '../../services/apiClient';
import { navigateTo } from '../../routes/AppRoutes';
import { listPayments } from './api';
import { PaymentBadge } from './PaymentBadge';
import { PaymentScheduleForm } from './PaymentForms';
import { PAYMENT_STATUS_LABELS } from './constants';
import type { PaymentSchedule } from './types';
const money=(v:number)=>new Intl.NumberFormat('vi-VN').format(v||0)+'đ';
export function PaymentsPage(){const [items,setItems]=useState<PaymentSchedule[]>([]); const [q,setQ]=useState(''); const [status,setStatus]=useState(''); const [errors,setErrors]=useState<string[]>([]); const load=useCallback(async()=>{try{const filters:Record<string,string>={}; if(q)filters.q=q;if(status)filters.status=status; const r=await listPayments(filters); setItems(r.data); setErrors([]);}catch(e){setErrors(formatApiError(e));}},[q,status]); useEffect(()=>{void load();},[load]); return <section className="admin-page"><header className="page-header"><div><p>Payment Management</p><h1>Thanh toán</h1><span>Quản lý lịch thanh toán, phiếu thu, phí phạt và hóa đơn nháp.</span></div></header>{errors.length>0&&<div className="form-error">{errors.join('. ')}</div>}<div className="filters"><input placeholder="Tìm mã thanh toán, hợp đồng, khách hàng, SĐT, deal" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(PAYMENT_STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={()=>void load()}>Lọc</button></div><PaymentScheduleForm onSaved={load}/><div className="table-wrapper"><table><thead><tr><th>Mã thanh toán</th><th>Hợp đồng</th><th>Khách hàng</th><th>Đợt</th><th>Hạn thanh toán</th><th>Phải thu</th><th>Đã thu</th><th>Còn lại</th><th>Phí phạt</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.payment_code}</td><td>{p.contract.contract_code}</td><td>{p.customer?.full_name || 'Chưa cập nhật'}<br/><small>{p.customer?.primary_phone}</small></td><td>{p.sequence_no}. {p.title}</td><td>{new Date(p.due_date).toLocaleDateString('vi-VN')}</td><td>{money(p.expected_amount)}</td><td>{money(p.paid_amount)}</td><td>{money(p.remaining_amount)}</td><td>{money(p.penalty_amount)}</td><td><PaymentBadge status={p.status}/></td><td><button onClick={()=>navigateTo(`/payments/${p.id}`)}>Chi tiết</button></td></tr>)}</tbody></table></div></section>}
