import { useEffect, useState } from 'react';
import { Modal } from '../../components/Modal';
import { GuideBox } from '../../components/help/GuideBox';
import { listAuditLogs, type AuditLog } from './api';
import { ACTION_LABELS, FIELD_LABELS, MODULE_LABELS } from './constants';

const fmt=(v:string)=>new Date(v).toLocaleString('vi-VN');
const json=(v:unknown)=>JSON.stringify(v??{},null,2);
const actionOpts=['','create','update','approve','cancel','hold','record_received','mark_paid','export','change_status','assign'];
const moduleOpts=['','sales_commission','company_commission','commission_payment_voucher','commission_payout_policy','commission_reconciliation_report','contract','payment','receipt','invoice','lead','customer','task'];
export function AuditLogsPage(){
 const [filters,setFilters]=useState<Record<string,string>>({page:'1',page_size:'20'}); const [items,setItems]=useState<AuditLog[]>([]); const [total,setTotal]=useState(0); const [selected,setSelected]=useState<AuditLog|null>(null); const [loading,setLoading]=useState(false);
 const set=(k:string,v:string)=>setFilters(f=>({...f,[k]:v,page:k==='page'?v:'1'}));
 useEffect(()=>{setLoading(true); listAuditLogs(filters).then(r=>{setItems(r.data.items);setTotal(r.data.total)}).finally(()=>setLoading(false));},[filters]);
 const page=Number(filters.page||1), pageSize=Number(filters.page_size||20);
 return <div className="audit-logs-page"><header className="page-header"><div><h1>Lịch sử thao tác</h1><p>Theo dõi ai đã thao tác gì, lúc nào, trên module nào và dữ liệu thay đổi ra sao.</p></div></header><GuideBox title="Cách dùng lịch sử thao tác" items={['Dùng để kiểm tra ai đã tạo, sửa, duyệt, hủy hoặc xác nhận dữ liệu quan trọng.','Có thể lọc theo người thao tác, module, hành động và thời gian.','Với các thao tác cập nhật, hệ thống hiển thị dữ liệu trước/sau nếu có.']} />
 <section className="card"><div className="filter-grid"><label>Từ ngày<input type="date" value={filters.date_from||''} onChange={e=>set('date_from',e.target.value)}/></label><label>Đến ngày<input type="date" value={filters.date_to||''} onChange={e=>set('date_to',e.target.value)}/></label><label>Người thao tác<input value={filters.actor_id||''} onChange={e=>set('actor_id',e.target.value)} placeholder="actor_id"/></label><label>Module<select value={filters.module||''} onChange={e=>set('module',e.target.value)}>{moduleOpts.map(m=><option key={m} value={m}>{m?MODULE_LABELS[m]: 'Tất cả'}</option>)}</select></label><label>Hành động<select value={filters.action||''} onChange={e=>set('action',e.target.value)}>{actionOpts.map(a=><option key={a} value={a}>{a?ACTION_LABELS[a]:'Tất cả'}</option>)}</select></label><label>Loại đối tượng<input value={filters.entity_type||''} onChange={e=>set('entity_type',e.target.value)}/></label><label>Mã đối tượng<input value={filters.entity_id||''} onChange={e=>set('entity_id',e.target.value)}/></label><label>Từ khóa<input value={filters.q||''} onChange={e=>set('q',e.target.value)}/></label></div></section>
 <section className="card audit-table-wrap"><table><thead><tr><th>Thời gian</th><th>Người thao tác</th><th>Module</th><th>Hành động</th><th>Đối tượng</th><th>Mô tả</th><th>Lý do</th><th>Chi tiết</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{fmt(i.created_at)}</td><td><strong>{i.actor_name||'Hệ thống'}</strong><br/><small>{i.actor_email}</small></td><td>{i.module_label||MODULE_LABELS[i.module]||i.module}</td><td><span className="badge">{i.action_label||ACTION_LABELS[i.action]||i.action}</span></td><td>{i.entity_label||`${i.entity_type} ${i.entity_id}`}</td><td>{i.description}</td><td>{i.reason}</td><td><button className="secondary-button" onClick={()=>setSelected(i)}>Xem chi tiết</button></td></tr>)}</tbody></table>{loading&&<p>Đang tải...</p>}<div className="pagination"><button disabled={page<=1} onClick={()=>set('page',String(page-1))}>Trước</button><span>Trang {page} / {Math.max(1,Math.ceil(total/pageSize))} · {total} dòng</span><button disabled={page>=Math.ceil(total/pageSize)} onClick={()=>set('page',String(page+1))}>Sau</button></div></section>
 {selected&&<Modal title="Chi tiết lịch sử thao tác" onClose={()=>setSelected(null)}><div className="modal-body audit-detail"><p><strong>Thời gian:</strong> {fmt(selected.created_at)}</p><p><strong>Người thao tác:</strong> {selected.actor_name||'Hệ thống'} {selected.actor_email}</p><p><strong>Module:</strong> {selected.module_label||MODULE_LABELS[selected.module]}</p><p><strong>Hành động:</strong> {selected.action_label||ACTION_LABELS[selected.action]}</p><p><strong>Đối tượng:</strong> {selected.entity_label||selected.entity_id}</p><p><strong>Mô tả:</strong> {selected.description}</p><p><strong>Lý do:</strong> {selected.reason||'—'}</p><p><strong>IP/User agent:</strong> {selected.ip_address||'—'} / {selected.user_agent||'—'}</p><h3>Trường thay đổi</h3>{selected.changed_fields&&Object.keys(selected.changed_fields).length?<table><tbody>{Object.entries(selected.changed_fields).map(([k,v])=><tr key={k}><td>{FIELD_LABELS[k]||k}</td><td>{String(v.before??'')}</td><td>{String(v.after??'')}</td></tr>)}</tbody></table>:<p>Không có dữ liệu thay đổi.</p>}<h3>Dữ liệu trước</h3><pre>{json(selected.before_data)}</pre><h3>Dữ liệu sau</h3><pre>{json(selected.after_data)}</pre></div></Modal>}
 </div>;
}
