export const ACTION_LABELS: Record<string,string>={
  'auth.login':'Đăng nhập','auth.logout':'Đăng xuất',create:'Tạo mới',update:'Cập nhật',delete:'Xóa',cancel:'Hủy',approve:'Duyệt',reject:'Từ chối',hold:'Tạm giữ',unhold:'Bỏ tạm giữ',mark_paid:'Xác nhận đã chi',mark_received:'Xác nhận đã nhận',record_received:'Ghi nhận đã nhận',assign:'Phân công',change_status:'Đổi trạng thái',export:'Xuất dữ liệu',create_voucher:'Lập phiếu chi',cancel_voucher:'Hủy phiếu chi',update_policy:'Cập nhật chính sách',
  'contracts.create':'Tạo hợp đồng','contracts.update':'Cập nhật hợp đồng','contracts.status_change':'Đổi trạng thái hợp đồng','contracts.delete':'Xóa hợp đồng','contracts.payment.create':'Tạo thanh toán hợp đồng','contracts.payment.confirm':'Xác nhận thanh toán hợp đồng',
  'bookings.create':'Tạo booking','bookings.update':'Cập nhật booking','bookings.status_change':'Đổi trạng thái booking','bookings.activity.create':'Thêm hoạt động booking','bookings.delete':'Xóa booking',
  'deals.create':'Tạo giao dịch','deals.create_from_booking':'Tạo giao dịch từ booking','deals.update':'Cập nhật giao dịch','deals.stage_change':'Đổi giai đoạn giao dịch','deals.status_change':'Đổi trạng thái giao dịch','deals.assign':'Phân công giao dịch','deals.add_activity':'Thêm hoạt động giao dịch','deals.delete':'Xóa giao dịch',
  'leads.create':'Tạo lead','leads.update':'Cập nhật lead','leads.status_change':'Đổi trạng thái lead','leads.assign':'Phân công lead','leads.transfer':'Chuyển lead','leads.reclaim':'Thu hồi lead','leads.convert':'Chuyển đổi lead','leads.delete':'Xóa lead',
  'customers.create':'Tạo khách hàng','customers.update':'Cập nhật khách hàng','customers.status_change':'Đổi trạng thái khách hàng','customers.assign':'Phân công khách hàng','customers.add_activity':'Thêm hoạt động khách hàng','customers.delete':'Xóa khách hàng',
  'inventory.properties.create':'Tạo bất động sản','inventory.properties.update':'Cập nhật bất động sản','inventory.properties.status_change':'Đổi trạng thái bất động sản','inventory.properties.price_update':'Cập nhật giá bất động sản','inventory.properties.delete':'Xóa bất động sản',
};
export const MODULE_LABELS: Record<string,string>={auth:'Xác thực',audit_log:'Lịch sử thao tác',system:'Hệ thống',sales_commission:'Hoa hồng sale',company_commission:'Hoa hồng công ty',commission_payment_voucher:'Phiếu chi hoa hồng',commission_payout_policy:'Chính sách chi hoa hồng',commission_reconciliation_report:'Báo cáo đối soát hoa hồng',contract:'Hợp đồng',contracts:'Hợp đồng',booking:'Booking / Giữ chỗ',bookings:'Booking / Giữ chỗ',deal:'Giao dịch',deals:'Giao dịch',payment:'Thanh toán',payments:'Thanh toán',receipt:'Phiếu thu',receipts:'Phiếu thu',invoice:'Hóa đơn',invoices:'Hóa đơn',lead:'Lead',leads:'Lead',customer:'Khách hàng',customers:'Khách hàng',task:'Công việc',tasks:'Công việc','inventory.properties':'Bất động sản',property_units:'Bất động sản',projects:'Dự án',users:'Người dùng',roles:'Vai trò',departments:'Phòng ban',teams:'Nhóm sale'};
export const FIELD_LABELS: Record<string,string>={status:'Trạng thái',amount:'Số tiền',received_amount:'Đã nhận',paid_amount:'Đã chi',approved_commission:'Hoa hồng duyệt',confirmed_receivable_amount:'Hoa hồng xác nhận',remaining_amount:'Còn lại',policy:'Chính sách',note:'Ghi chú',cancel_reason:'Lý do hủy',hold_reason:'Lý do tạm giữ',owner_id:'Người phụ trách',pipeline_stage:'Giai đoạn',inventory_status:'Trạng thái kho'};
export function humanizeTechnical(value?: string | null){const text=(value||'').trim(); if(!text||text==='null'||text==='undefined') return ''; return text.split('.').pop()!.split('_').filter(Boolean).map(w=>w[0]?.toUpperCase()+w.slice(1)).join(' ');}
export const labelAction=(value?:string|null)=>ACTION_LABELS[(value||'').trim()]||humanizeTechnical(value)||'Không xác định';
export function inferModuleFromAction(module?:string|null, action?:string|null){const stale=!module||['audit_log','system','unknown','null','undefined'].includes(String(module).trim()); if(!stale) return module; const a=action||''; if(a.startsWith('inventory.properties.')) return 'inventory.properties'; const prefix=a.split('.',1)[0]; if(prefix==='commissions') return 'sales_commission'; return prefix||module||'system';}
export const labelModule=(value?:string|null)=>MODULE_LABELS[(value||'').trim()]||humanizeTechnical(value)||'Hệ thống';
export const labelField=(value:string)=>FIELD_LABELS[value]||humanizeTechnical(value)||value;
export const ENTITY_TYPE_LABELS: Record<string,string>={user:'Người dùng',contract:'Hợp đồng',contracts:'Hợp đồng',booking:'Booking',bookings:'Booking',deal:'Giao dịch',deals:'Giao dịch',lead:'Lead',leads:'Lead',customer:'Khách hàng',customers:'Khách hàng',sales_commission:'Hoa hồng sale',company_commission:'Hoa hồng công ty',commission_payment_voucher:'Phiếu chi hoa hồng',property_units:'Bất động sản',audit_log:'Lịch sử thao tác',system:'Hệ thống'};
