import { useCallback, useEffect, useState } from 'react';
import { can } from '../auth/authStore';
import { navigateTo } from '../../routes/AppRoutes';
import { downloadFinanceCsv, cashCollection, financeSummary, invoiceReport, overduePayments, receivables } from './api';
import { AGING_BUCKET_LABELS, FINANCE_REPORT_EXPORT_PERMISSION, FINANCE_REPORT_VIEW_PERMISSION } from './constants';
import type { CashCollectionReport, FinanceSummary, InvoiceReport, OverduePaymentRow, Paginated, ReceivableRow } from './types';

const vnd=(n?:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n||0));
const dateText=(value?:string)=>value?new Date(value).toLocaleDateString('vi-VN'):'-';
const empty=<tr><td colSpan={20} className="muted">Không có dữ liệu phù hợp.</td></tr>;

type Tab='overview'|'receivables'|'overdue-payments'|'cash-collection'|'invoices';

export function FinanceReportsPage(){
  const [tab,setTab]=useState<Tab>('overview');
  const [filters,setFilters]=useState<Record<string,string>>({page:'1',page_size:'20'});
  const [draft,setDraft]=useState<Record<string,string>>({});
  const [summary,setSummary]=useState<FinanceSummary|null>(null);
  const [recv,setRecv]=useState<Paginated<ReceivableRow>|null>(null);
  const [overdue,setOverdue]=useState<Paginated<OverduePaymentRow>|null>(null);
  const [cash,setCash]=useState<CashCollectionReport|null>(null);
  const [invoices,setInvoices]=useState<InvoiceReport|null>(null);
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [exportError,setExportError]=useState('');
  const canExport=can(FINANCE_REPORT_EXPORT_PERMISSION);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [s,r,o,c,i]=await Promise.all([financeSummary(filters),receivables(filters),overduePayments(filters),cashCollection(filters),invoiceReport(filters)]);setSummary(s.data);setRecv(r.data);setOverdue(o.data);setCash(c.data);setInvoices(i.data);}catch(e){setError(e instanceof Error?e.message:'Không tải được báo cáo tài chính.');}finally{setLoading(false);}},[filters]);
  useEffect(()=>{void load();},[load]);
  if(!can(FINANCE_REPORT_VIEW_PERMISSION)) return <section className="admin-page"><h1>Báo cáo tài chính</h1><p className="error-text">Bạn không có quyền xem báo cáo tài chính.</p></section>;
  const doExport=async(report:string)=>{setExportError('');try{await downloadFinanceCsv(report,filters);}catch(e){setExportError(e instanceof Error?e.message:'Xuất CSV thất bại.');}};
  return <section className="admin-page"><header className="page-header"><div><h1>Báo cáo tài chính</h1><p>Theo dõi công nợ, dòng tiền thu và hóa đơn.</p></div></header>
    <div className="filter-panel"><input type="date" value={draft.date_from||''} onChange={e=>setDraft({...draft,date_from:e.target.value})}/><input type="date" value={draft.date_to||''} onChange={e=>setDraft({...draft,date_to:e.target.value})}/><input placeholder="Tìm khách hàng" value={draft.customer||''} onChange={e=>setDraft({...draft,customer:e.target.value})}/><input placeholder="Mã hợp đồng" value={draft.contract_code||''} onChange={e=>setDraft({...draft,contract_code:e.target.value})}/><select value={draft.contract_status||''} onChange={e=>setDraft({...draft,contract_status:e.target.value})}><option value="">Trạng thái HĐ</option><option value="draft">Nháp</option><option value="active">Hiệu lực</option><option value="completed">Hoàn tất</option><option value="cancelled">Đã hủy</option></select><button onClick={()=>setFilters({...draft,page:'1',page_size:'20'})}>Lọc</button><button className="secondary-button" onClick={()=>{setDraft({});setFilters({page:'1',page_size:'20'});}}>Xóa lọc</button></div>
    {error && <p className="error-text">{error}</p>}{exportError && <p className="error-text">{exportError}</p>}{loading && <p>Đang tải báo cáo...</p>}
    {summary && <div className="summary-grid">{[['Tổng giá trị hợp đồng',vnd(summary.total_contract_value)],['Tổng tiền cọc',vnd(summary.total_deposit_value)],['Tổng đã thu',vnd(summary.total_collected_with_deposit)],['Tổng còn phải thu',vnd(summary.total_remaining)],['HĐ thanh toán đủ',summary.paid_contract_count],['HĐ còn công nợ',summary.receivable_contract_count],['PMT quá hạn',summary.overdue_payment_count],['Tiền quá hạn',vnd(summary.total_overdue_amount)],['Phiếu thu xác nhận',summary.confirmed_receipt_count],['Tiền phiếu thu xác nhận',vnd(summary.total_confirmed_receipts)],['Hóa đơn phát hành',summary.issued_invoice_count],['Giá trị hóa đơn phát hành',vnd(summary.issued_invoice_amount)]].map(([k,v])=><div className="summary-card" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div>}
    <div className="tabs">{[['overview','Tổng quan'],['receivables','Công nợ hợp đồng'],['overdue-payments','PMT quá hạn'],['cash-collection','Dòng tiền đã thu'],['invoices','Hóa đơn']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id as Tab)}>{label}</button>)}</div>
    {tab==='overview' && <p className="muted">Chọn từng tab để xem chi tiết và xuất CSV từng báo cáo.</p>}
    {tab==='receivables' && <ReportSection title="Công nợ hợp đồng" exportName="receivables" canExport={canExport} onExport={doExport}><table><thead><tr><th>Mã HĐ</th><th>Khách hàng</th><th>Sale</th><th>Giá trị HĐ</th><th>Cọc</th><th>Đã thu</th><th>Còn lại</th><th>Quá hạn</th><th>Nhóm tuổi nợ</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody>{recv?.items.length?recv.items.map(i=><tr key={i.contract_id}><td><a onClick={()=>navigateTo(`/contracts/${i.contract_id}`)}>{i.contract_code}</a></td><td>{i.customer_name}</td><td>{i.sale_name||'-'}</td><td>{vnd(i.contract_value)}</td><td>{vnd(i.deposit_value)}</td><td>{vnd(i.total_collected_amount)}</td><td>{vnd(i.remaining_amount)}</td><td>{vnd(i.overdue_amount)}</td><td>{AGING_BUCKET_LABELS[i.aging_bucket]}</td><td>{i.contract_status_label}</td><td><button onClick={()=>navigateTo(`/contracts/${i.contract_id}`)}>Xem</button></td></tr>):empty}</tbody></table></ReportSection>}
    {tab==='overdue-payments' && <ReportSection title="PMT quá hạn" exportName="overdue-payments" canExport={canExport} onExport={doExport}><table><thead><tr><th>Mã PMT</th><th>Mã HĐ</th><th>Khách hàng</th><th>Đợt</th><th>Ngày đến hạn</th><th>Phải thu</th><th>Đã thu</th><th>Còn lại</th><th>Số ngày quá hạn</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody>{overdue?.items.length?overdue.items.map(i=><tr key={i.payment_id}><td><a onClick={()=>navigateTo(`/payments/${i.payment_id}`)}>{i.payment_code}</a></td><td><a onClick={()=>navigateTo(`/contracts/${i.contract_id}`)}>{i.contract_code}</a></td><td>{i.customer_name}</td><td>{i.installment_name}</td><td>{dateText(i.due_date)}</td><td>{vnd(i.amount_due)}</td><td>{vnd(i.paid_amount)}</td><td>{vnd(i.remaining_amount)}</td><td>{i.overdue_days}</td><td>{i.payment_status_label}</td><td><button onClick={()=>navigateTo(`/payments/${i.payment_id}`)}>Xem</button></td></tr>):empty}</tbody></table></ReportSection>}
    {tab==='cash-collection' && <ReportSection title="Dòng tiền đã thu" exportName="cash-collection" canExport={canExport} onExport={doExport}><table><thead><tr><th>Mã phiếu thu</th><th>Ngày thu</th><th>Khách hàng</th><th>Mã HĐ</th><th>Mã PMT</th><th>Số tiền</th><th>Phương thức</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody>{cash?.items.length?cash.items.map(i=><tr key={i.receipt_id}><td><a onClick={()=>navigateTo(`/receipts/${i.receipt_id}`)}>{i.receipt_code}</a></td><td>{dateText(i.receipt_date)}</td><td>{i.customer_name}</td><td><a onClick={()=>navigateTo(`/contracts/${i.contract_id}`)}>{i.contract_code}</a></td><td><a onClick={()=>navigateTo(`/payments/${i.payment_id}`)}>{i.payment_code}</a></td><td>{vnd(i.amount)}</td><td>{i.payment_method_label||'-'}</td><td>{i.status_label}</td><td><button onClick={()=>navigateTo(`/receipts/${i.receipt_id}`)}>Xem</button></td></tr>):empty}</tbody></table></ReportSection>}
    {tab==='invoices' && <ReportSection title="Hóa đơn" exportName="invoices" canExport={canExport} onExport={doExport}><table><thead><tr><th>Mã hóa đơn</th><th>Ngày phát hành</th><th>Khách hàng</th><th>Mã HĐ</th><th>Mã PMT</th><th>Mã phiếu thu</th><th>Số tiền</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody>{invoices?.items.length?invoices.items.map(i=><tr key={i.invoice_id}><td><a onClick={()=>navigateTo(`/invoices/${i.invoice_id}`)}>{i.invoice_code}</a></td><td>{dateText(i.issued_date)}</td><td>{i.customer_name}</td><td><a onClick={()=>navigateTo(`/contracts/${i.contract_id}`)}>{i.contract_code}</a></td><td>{i.payment_id?<a onClick={()=>navigateTo(`/payments/${i.payment_id}`)}>{i.payment_code}</a>:'-'}</td><td>{i.receipt_id?<a onClick={()=>navigateTo(`/receipts/${i.receipt_id}`)}>{i.receipt_code}</a>:'-'}</td><td>{vnd(i.amount)}</td><td>{i.status_label}</td><td><button onClick={()=>navigateTo(`/invoices/${i.invoice_id}`)}>Xem</button></td></tr>):empty}</tbody></table></ReportSection>}
  </section>;
}
function ReportSection({title,exportName,canExport,onExport,children}:{title:string;exportName:string;canExport:boolean;onExport:(r:string)=>void;children:React.ReactNode}){return <div className="table-card"><div className="table-toolbar"><h2>{title}</h2>{canExport&&<button onClick={()=>onExport(exportName)}>Xuất CSV</button>}</div>{children}</div>}
